window.TM=window.TM||{};
TM.Actions=(()=>{
 const TYPES=['Block Internal IP','Block External IP','Block Domain / URL','Disable Account','Isolate Endpoint','Change Firewall Rule','Change Domain Policy','Other'];
 const clean=v=>String(v??'').trim();
 async function list(){return (await TM.Store.list('actionRecord')).filter(x=>!x._corrupt).sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))}
 async function get(id){return TM.Store.get('actionRecord',id)}
 async function create(actorId,{actionType,target,reason,details='',impact='',evidence='',groupId=null}){actionType=clean(actionType);target=clean(target);reason=clean(reason);if(!actionType||!target||!reason)throw Error('Action, target and reason are required');return TM.Store.createActionRecord({actorId,actionType,target,reason,details:clean(details),impact:clean(impact),evidence:clean(evidence),groupId:groupId||null})}
 async function comments(id){const base=(await TM.Store.list('actionComment')).filter(x=>!x._corrupt&&x.actionId===id),events=(await TM.Store.list('actionCommentEvent')).filter(x=>!x._corrupt).sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt))||a.id.localeCompare(b.id)),map=new Map(base.map(x=>[x.id,{...x,edited:false,deleted:false}]));for(const e of events){const x=map.get(e.commentId);if(!x)continue;if(e.action==='edit'){x.html=e.value;x.edited=true;x.editedAt=e.createdAt}if(e.action==='delete'){x.deleted=true;x.deletedAt=e.createdAt;x.deletedBy=e.actorId}}return [...map.values()].sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)))}
 async function addComment(actorId,id,html,attachments=[]){await get(id);html=String(html||'').trim();if(!html&&!attachments.length)throw Error('Comment or attachment required');return TM.Store.addActionComment({actionId:id,authorId:actorId,html:html||'<p></p>',attachments})}
 async function changeComment(actorId,id,commentId,action,html=''){await get(id);const row=(await comments(id)).find(x=>x.id===commentId);if(!row)throw Error('Comment not found');const admin=await TM.Auth.can(actorId,'*');if(row.authorId!==actorId&&!admin)throw Error('Only the comment author or Administrator can modify this comment');if(row.deleted)throw Error('Comment already deleted');if(action==='edit'){html=String(html||'').trim();if(!html)throw Error('Comment cannot be empty');return TM.Store.addActionCommentEvent({commentId,actorId,action:'edit',value:html})}if(action==='delete')return TM.Store.addActionCommentEvent({commentId,actorId,action:'delete'});throw Error('Invalid comment action')}
 return{TYPES,list,get,create,comments,addComment,changeComment};
})();
