window.TM=window.TM||{};
TM.Admin=(()=>{
 async function requirePermission(actorId,p){if(!await TM.Auth.can(actorId,p))throw Error('Permission denied: '+p)}
 async function createUser(actorId,{username,displayName,password,roleId=null,groupId=null}){await requirePermission(actorId,'users.create');username=String(username||'').trim().toLowerCase();displayName=String(displayName||'').trim();if(!username||!displayName)throw Error('username and displayName required');if(await TM.Auth.findUser(username))throw Error('Username already exists');const pw=await TM.Auth.passwordRecord(password),u=await TM.Store.createUser({username,displayName,...pw});if(roleId)await TM.Store.addMembership({userId:u.id,groupId,roleId});return u}
 async function createGroup(actorId,{name,description=''}){await requirePermission(actorId,'groups.manage');name=String(name||'').trim();if(!name)throw Error('group name required');if((await TM.Store.list('group')).some(g=>!g._corrupt&&String(g.name).toLowerCase()===name.toLowerCase()))throw Error('Group already exists');return TM.Store.createGroup({name,description:String(description||'').trim()})}
 async function editGroup(actorId,groupId,values){await requirePermission(actorId,'groups.manage');return TM.Identity.setGroupDetails(groupId,values,actorId)}\n async function setGroupEnabled(actorId,groupId,value){await requirePermission(actorId,'groups.manage');return TM.Identity.setGroupEnabled(groupId,value,actorId)}\n async function assignRole(actorId,{userId,roleId,groupId=null}){await requirePermission(actorId,'users.edit');for(const m of await TM.Store.list('membership')){if(m._corrupt||m.userId!==userId||m.roleId!==roleId||m.groupId!==groupId)continue;if((await TM.Identity.membershipState(m)).enabled)throw Error('Active membership already exists')}return TM.Store.addMembership({userId,roleId,groupId})}
 async function setUserEnabled(actorId,userId,value){await requirePermission(actorId,'users.disable');return TM.Identity.setUserEnabled(userId,value,actorId)}
 async function setMembershipEnabled(actorId,membershipId,value){await requirePermission(actorId,'users.edit');return TM.Identity.setMembershipEnabled(membershipId,value,actorId)}
 async function setDisplayName(actorId,userId,value){await requirePermission(actorId,'users.edit');return TM.Identity.setDisplayName(userId,value,actorId)}
 return{createUser,createGroup,editGroup,setGroupEnabled,assignRole,setUserEnabled,setMembershipEnabled,setDisplayName};
})();