(()=>{
window.TM=window.TM||{};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const validColor=c=>/^#[0-9a-f]{6}$/i.test(c||'')?c:'#f8fafc';
function active(a,now=Date.now()){if(a.enabled===false)return false;const start=a.startAt?new Date(a.startAt).getTime():0,end=a.endAt?new Date(a.endAt).getTime():Infinity;return now>=start&&now<=end}
async function list(){return (await TM.DB.getAll('announcements')).sort((a,b)=>(b.createdAt||'').localeCompare(a.createdAt||''))}
async function create(data,actor){const text=String(data.text||'').trim();if(!text)throw Error('Announcement text is required.');const startAt=data.startAt?new Date(data.startAt).toISOString():new Date().toISOString(),endAt=data.endAt?new Date(data.endAt).toISOString():'';if(endAt&&new Date(endAt)<=new Date(startAt))throw Error('End time must be after start time.');const row={text,startAt,endAt,bold:!!data.bold,italic:!!data.italic,underline:!!data.underline,color:validColor(data.color),enabled:true,createdAt:new Date().toISOString(),createdBy:actor?.id||null};const id=await TM.DB.add('announcements',row);await TM.DB.audit('ANNOUNCEMENT_CREATED','announcement',id,{startAt,endAt});await refreshMarquee();return id}
async function remove(id){await TM.DB.remove('announcements',Number(id));await TM.DB.audit('ANNOUNCEMENT_DELETED','announcement',id,{});await refreshMarquee()}
async function toggle(id){const a=await TM.DB.get('announcements',Number(id));if(!a)return;a.enabled=a.enabled===false;await TM.DB.put('announcements',a);await TM.DB.audit(a.enabled?'ANNOUNCEMENT_ENABLED':'ANNOUNCEMENT_DISABLED','announcement',id,{});await refreshMarquee()}
async function refreshMarquee(){const host=document.querySelector('#announcement-marquee-host');if(!host)return;const rows=(await list()).filter(a=>active(a));if(!rows.length){host.innerHTML='';host.hidden=true;return}host.hidden=false;host.innerHTML=`<div class="announcement-marquee"><div class="announcement-marquee-track">${rows.map(a=>`<span style="color:${validColor(a.color)};font-weight:${a.bold?'700':'400'};font-style:${a.italic?'italic':'normal'};text-decoration:${a.underline?'underline':'none'}">${esc(a.text)}</span>`).join('<span class="announcement-separator">◆</span>')}</div></div>`}
async function page(){const rows=await list(),root=document.querySelector('#page-content'),actor=await TM.Auth.currentUser();root.innerHTML=`<div class="page-head"><div><h1>Announcements</h1><p class="muted">Scheduled organization marquee messages</p></div><button id="announcement-new">+ New announcement</button></div><div class="card"><div class="table-wrap"><table><thead><tr><th>Announcement</th><th>Starts</th><th>Ends</th><th>Status</th><th>Actions</th></tr></thead><tbody>${rows.length?rows.map(a=>`<tr><td><span style="color:${validColor(a.color)};font-weight:${a.bold?'700':'400'};font-style:${a.italic?'italic':'normal'};text-decoration:${a.underline?'underline':'none'}">${esc(a.text)}</span></td><td>${new Date(a.startAt).toLocaleString()}</td><td>${a.endAt?new Date(a.endAt).toLocaleString():'No expiry'}</td><td><span class="badge">${a.enabled===false?'Disabled':active(a)?'Active':Date.now()<new Date(a.startAt).getTime()?'Scheduled':'Expired'}</span></td><td><button class="secondary" data-ann-toggle="${a.id}">${a.enabled===false?'Enable':'Disable'}</button> <button class="secondary" data-ann-delete="${a.id}">Delete</button></td></tr>`).join(''):'<tr><td colspan="5" class="muted">No announcements yet.</td></tr>'}</tbody></table></div></div>`;document.querySelector('#announcement-new').onclick=()=>editor(actor);document.querySelectorAll('[data-ann-toggle]').forEach(b=>b.onclick=async()=>{await toggle(b.dataset.annToggle);page()});document.querySelectorAll('[data-ann-delete]').forEach(b=>b.onclick=async()=>{if(confirm('Delete this announcement?')){await remove(b.dataset.annDelete);page()}})}
function editor(actor){const r=document.querySelector('#modal-root'),now=new Date(),later=new Date(Date.now()+86400000),local=d=>new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);r.innerHTML=`<div class="modal-backdrop"><div class="modal announcement-editor"><h2>New announcement</h2><p class="muted">The message appears as a marquee only during its active time period.</p><div id="ann-msg" class="hidden"></div><form id="ann-form" class="form-grid"><label>Message<textarea name="text" id="ann-text" rows="3" maxlength="500" required placeholder="Type announcement…"></textarea></label><div class="announcement-formatbar"><button type="button" data-ann-fmt="bold"><strong>B</strong></button><button type="button" data-ann-fmt="italic"><em>I</em></button><button type="button" data-ann-fmt="underline"><u>U</u></button><label title="Text color">A <input type="color" name="color" id="ann-color" value="#f8fafc"></label></div><div class="announcement-time-grid"><label>Start date/time<input type="datetime-local" name="startAt" value="${local(now)}" required></label><label>End date/time<input type="datetime-local" name="endAt" value="${local(later)}"></label></div><div class="announcement-preview"><span>Preview</span><div id="ann-preview">Announcement preview</div></div><div class="modal-actions"><button type="button" class="secondary" id="ann-cancel">Cancel</button><button>Publish / Schedule</button></div></form></div></div>`;let bold=false,italic=false,underline=false;const text=r.querySelector('#ann-text'),color=r.querySelector('#ann-color'),preview=r.querySelector('#ann-preview');function draw(){preview.textContent=text.value||'Announcement preview';preview.style.color=color.value;preview.style.fontWeight=bold?'700':'400';preview.style.fontStyle=italic?'italic':'normal';preview.style.textDecoration=underline?'underline':'none'}r.querySelectorAll('[data-ann-fmt]').forEach(b=>b.onclick=()=>{const k=b.dataset.annFmt;if(k==='bold')bold=!bold;if(k==='italic')italic=!italic;if(k==='underline')underline=!underline;b.classList.toggle('active',k==='bold'?bold:k==='italic'?italic:underline);draw()});text.oninput=draw;color.oninput=draw;r.querySelector('#ann-cancel').onclick=()=>r.innerHTML='';r.querySelector('#ann-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);try{await create({text:f.get('text'),startAt:f.get('startAt'),endAt:f.get('endAt'),color:f.get('color'),bold,italic,underline},actor);r.innerHTML='';page()}catch(x){const m=r.querySelector('#ann-msg');m.textContent=x.message;m.className='error'}};draw()}
TM.Announcements={page,create,list,refreshMarquee};
setInterval(refreshMarquee,30000);
})();