(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let activeUrl=null;
function ext(name=''){return(name.split('.').pop()||'').toLowerCase()}function close(){if(activeUrl){URL.revokeObjectURL(activeUrl);activeUrl=null}const r=document.querySelector('#modal-root');if(r)r.innerHTML=''}
async function spreadsheet(blob){if(!window.XLSX)return '<div class="attachment-empty">Spreadsheet preview engine is unavailable.</div>';try{const ab=await blob.arrayBuffer(),wb=XLSX.read(ab,{type:'array'}),tabs=wb.SheetNames.map((n,i)=>`<button class="sheet-tab ${i?'secondary':''}" data-sheet="${i}">${esc(n)}</button>`).join(''),sheets=wb.SheetNames.map((n,i)=>`<div class="sheet-pane ${i?'hidden':''}" data-sheet-pane="${i}">${XLSX.utils.sheet_to_html(wb.Sheets[n])}</div>`).join('');return `<div class="sheet-tabs">${tabs}</div><div class="sheet-preview">${sheets}</div>`}catch(e){return `<div class="attachment-empty">Could not preview spreadsheet: ${esc(e.message)}</div>`}}
async function textPreview(blob,isRtf=false){try{let t=await blob.text();if(isRtf)t=t.replace(/\\par[d]?/g,'\n').replace(/\\'[0-9a-f]{2}/gi,'').replace(/\\[a-z]+-?\d* ?/gi,'').replace(/[{}]/g,'').trim();return `<pre class="text-preview">${esc(t)}</pre>`}catch{return '<div class="attachment-empty">Could not read text.</div>'}}
async function open(id){const a=await TM.DB.get('attachments',Number(id));if(!a||!a.blob)return;const r=document.querySelector('#modal-root'),x=ext(a.name);let body='';if(/^(png|jpg|jpeg|gif|webp|bmp|svg)$/.test(x)){activeUrl=URL.createObjectURL(a.blob);body=`<div class="image-preview"><img src="${activeUrl}" alt="${esc(a.name)}"></div>`}else if(x==='pdf'){activeUrl=URL.createObjectURL(a.blob);body=`<iframe class="document-frame" src="${activeUrl}" title="${esc(a.name)}"></iframe>`}else if(/^(txt|log|csv|md)$/.test(x))body=await textPreview(a.blob);else if(x==='rtf')body=await textPreview(a.blob,true);else if(/^(xls|xlsx)$/.test(x))body=await spreadsheet(a.blob);else if(/^(doc|docx)$/.test(x))body=`<div class="office-preview"><div class="office-icon">W</div><h3>${esc(a.name)}</h3><p>Word files are stored intact. Full DOC/DOCX rendering needs the local document-renderer stage; until then use Save copy to open it in your installed office application.</p></div>`;else body='<div class="attachment-empty">Preview is not available for this file type.</div>';
r.innerHTML=`<div class="modal-backdrop attachment-backdrop"><div class="attachment-modal"><header><div class="attachment-title"><strong>${esc(a.name)}</strong><span>${Math.ceil(a.size/1024)} KB · ${esc(x.toUpperCase())}</span></div><div class="attachment-header-actions"><button class="secondary" id="attachment-save">Save copy</button><button class="secondary attachment-x" id="attachment-close" aria-label="Close">×</button></div></header><main>${body}</main></div></div>`;document.querySelector('#attachment-close').onclick=close;document.querySelector('.attachment-backdrop').onclick=e=>{if(e.target===e.currentTarget)close()};document.querySelector('#attachment-save').onclick=()=>download(a);document.querySelectorAll('.sheet-tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.sheet-tab').forEach(x=>x.classList.add('secondary'));b.classList.remove('secondary');document.querySelectorAll('[data-sheet-pane]').forEach(x=>x.classList.toggle('hidden',x.dataset.sheetPane!==b.dataset.sheet))})}
function download(a){const u=URL.createObjectURL(a.blob),link=document.createElement('a');link.href=u;link.download=a.name;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
async function resolveTimeline(hit){const rows=await TM.DB.getAll('attachments');const raw=hit.textContent.replace(/^\s*📎\s*/,'').replace(/\s*\([^)]*KB\)\s*$/,'').trim(),matches=rows.filter(a=>a.name===raw&&a.blob);if(!matches.length)return;matches.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));open(matches[0].id)}
document.addEventListener('click',e=>{const direct=e.target.closest('[data-attachment-id]');if(direct){e.preventDefault();e.stopPropagation();open(direct.dataset.attachmentId);return}const timeline=e.target.closest('.timeline-attachment');if(timeline){e.preventDefault();e.stopPropagation();resolveTimeline(timeline)}});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.querySelector('.attachment-modal'))close()});window.TM=window.TM||{};TM.AttachmentViewer={open,close};
})();
