(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let activeUrl=null;
function ext(name=''){return(name.split('.').pop()||'').toLowerCase()}function close(){if(activeUrl){URL.revokeObjectURL(activeUrl);activeUrl=null}const r=document.querySelector('#modal-root');if(r)r.innerHTML=''}
async function spreadsheet(blob){if(!window.XLSX)return '<div class="attachment-empty">Spreadsheet preview engine is unavailable.</div>';try{const ab=await blob.arrayBuffer(),wb=XLSX.read(ab,{type:'array'}),name=wb.SheetNames[0],html=XLSX.utils.sheet_to_html(wb.Sheets[name]);return `<div class="sheet-preview-head">Sheet: ${esc(name)}</div><div class="sheet-preview">${html}</div>`}catch(e){return `<div class="attachment-empty">Could not preview spreadsheet: ${esc(e.message)}</div>`}}
async function textPreview(blob,isRtf=false){try{let t=await blob.text();if(isRtf)t=t.replace(/\\par[d]?/g,'\n').replace(/\\'[0-9a-f]{2}/gi,'').replace(/\\[a-z]+-?\d* ?/gi,'').replace(/[{}]/g,'').trim();return `<pre class="text-preview">${esc(t)}</pre>`}catch(e){return `<div class="attachment-empty">Could not read text.</div>`}}
async function open(id){const a=await TM.DB.get('attachments',Number(id));if(!a||!a.blob)return;const r=document.querySelector('#modal-root'),x=ext(a.name);let body='';if(/^(png|jpg|jpeg|gif|webp|bmp|svg)$/.test(x)){activeUrl=URL.createObjectURL(a.blob);body=`<div class="image-preview"><img src="${activeUrl}" alt="${esc(a.name)}"></div>`}else if(x==='pdf'){activeUrl=URL.createObjectURL(a.blob);body=`<iframe class="document-frame" src="${activeUrl}" title="${esc(a.name)}"></iframe>`}else if(/^(txt|log|csv|md)$/.test(x))body=await textPreview(a.blob);else if(x==='rtf')body=await textPreview(a.blob,true);else if(/^(xls|xlsx)$/.test(x))body=await spreadsheet(a.blob);else if(/^(doc|docx)$/.test(x)){activeUrl=URL.createObjectURL(a.blob);body=`<div class="office-preview"><div class="office-icon">W</div><h3>${esc(a.name)}</h3><p>Browser-native Word rendering is not available in standalone mode. The original document is stored locally and can be opened with your installed office application.</p><button id="attachment-open-external">Open document</button></div>`}else body='<div class="attachment-empty">Preview is not available for this file type.</div>';
r.innerHTML=`<div class="modal-backdrop attachment-backdrop"><div class="attachment-modal"><header><div><strong>${esc(a.name)}</strong><span>${Math.ceil(a.size/1024)} KB</span></div><div class="attachment-header-actions"><button class="secondary" id="attachment-save">Save copy</button><button class="secondary attachment-x" id="attachment-close" aria-label="Close">×</button></div></header><main>${body}</main></div></div>`;document.querySelector('#attachment-close').onclick=close;document.querySelector('.attachment-backdrop').onclick=e=>{if(e.target===e.currentTarget)close()};document.querySelector('#attachment-save').onclick=()=>download(a);const external=document.querySelector('#attachment-open-external');if(external)external.onclick=()=>download(a)}
function download(a){const u=URL.createObjectURL(a.blob),link=document.createElement('a');link.href=u;link.download=a.name;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(u),1000)}
document.addEventListener('click',e=>{const hit=e.target.closest('[data-attachment-id]');if(!hit)return;e.preventDefault();e.stopPropagation();open(hit.dataset.attachmentId)});document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.querySelector('.attachment-modal'))close()});window.TM=window.TM||{};TM.AttachmentViewer={open,close};
})();
