window.TM=window.TM||{};
TM.Auth=(()=>{
 const enc=new TextEncoder(),ITERATIONS=210000;
 const b64=b=>btoa(String.fromCharCode(...new Uint8Array(b))),unb64=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
 async function derive(password,salt,iterations=ITERATIONS){const key=await crypto.subtle.importKey('raw',enc.encode(password),'PBKDF2',false,['deriveBits']);return b64(await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt,iterations},key,256))}
 async function passwordRecord(password){if(typeof password!=='string'||password.length<12)throw Error('Password must be at least 12 characters');const salt=crypto.getRandomValues(new Uint8Array(16));return{passwordHash:await derive(password,salt),passwordSalt:b64(salt),passwordIterations:ITERATIONS,passwordAlgorithm:'PBKDF2-SHA256'}}
 async function verifyPassword(password,user){if(!user.passwordHash||!user.passwordSalt)return false;const actual=await derive(password,unb64(user.passwordSalt),user.passwordIterations||ITERATIONS),expected=user.passwordHash;let diff=actual.length^expected.length;for(let i=0;i<Math.min(actual.length,expected.length);i++)diff|=actual.charCodeAt(i)^expected.charCodeAt(i);return diff===0}
 async function findUser(username){const base=(await TM.Store.list('user')).find(u=>!u._corrupt&&u.username.toLowerCase()===String(username).toLowerCase());return base&&TM.Identity?TM.Identity.userState(base.id):base||null}
 async function firstAdmin({username,displayName,password}){await TM.Store.bootstrapSystem();if((await TM.Store.list('user')).some(u=>!u._corrupt))throw Error('Users already exist; first-admin bootstrap closed');const pw=await passwordRecord(password),u=await TM.Store.createUser({username:String(username).trim().toLowerCase(),displayName:String(displayName).trim(),...pw}),role=(await TM.Store.list('role')).find(r=>r.systemKey==='administrator');await TM.Store.addMembership({userId:u.id,roleId:role.id});return u}
 async function permissions(userId){const roles=await TM.Store.list('role'),set=new Set();for(const m of await TM.Store.list('membership')){if(m._corrupt||m.userId!==userId)continue;const state=TM.Identity?await TM.Identity.membershipState(m):m;if(!state.enabled)continue;const r=roles.find(x=>x.id===m.roleId);if(r)for(const p of r.permissions||[])set.add(p)}return set}
 async function can(userId,permission){const p=await permissions(userId);return p.has('*')||p.has(permission)}
 async function login(username,password){const u=await findUser(username);if(!u||!u.enabled||!await verifyPassword(password,u))throw Error('Invalid username or password');const session=await TM.Store.create('session',{userId:u.id,token:crypto.randomUUID()+crypto.randomUUID(),expiresAt:new Date(Date.now()+28800000).toISOString(),enabled:true});return{user:u,session}}
 return{ITERATIONS,passwordRecord,verifyPassword,findUser,firstAdmin,permissions,can,login};
})();