window.TM=window.TM||{};
TM.Documents=(()=>{
 const BASE=['Task-Management-Data','Documents','Files'],esc=v=>{const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML};
 let objectUrl=null;
 async function list(){const docs=(await TM.Store.list('document')).filter(x=>!x._corrupt),events=(await TM.Store.list('documentEvent')).filter(x=>!x._corrupt).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)),map=new Map(docs.map(x=>[x.id,{...x}]));for(const e of events){const x=map.get(e.documentId);if(!x)continue;if(e.action==='archive')x.status='Archived';if(e.action==='restore')x.status='Active'}return [...map.values()].sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)))}
 async function upload(file,actorId,parentType=null,parentId=null){if(!file||file.type!=='application/pdf'&&!file.name.toLowerCase().endsWith('.pdf'))throw Error('Select a PDF file');if(file.size<5)throw Error('PDF is empty or invalid');const head=new Uint8Array(await file.slice(0,5).arrayBuffer());if(String.fromCharCode(...head)!=='%PDF-')throw Error('File does not contain a valid PDF header');const hash=[...new Uint8Array(await crypto.subtle.digest('SHA-256',await file.arrayBuffer()))].map(x=>x.toString(16).padStart(2,'0')).join(''),existing=await list(),same=existing.filter(x=>x.sha256===hash&&x.status!=='Archived'),sameParent=same.find(x=>x.parentType===parentType&&x.parentId===parentId);if(sameParent)throw Error('This exact PDF is already attached to this '+(parentType||'record'));const safe=file.name.replace(/[^a-zA-Z0-9._ -]/g,'_');if(same.length){const where=[...new Set(same.map(x=>x.parentType&&x.parentId?x.parentType+' '+x.parentId:'Document Review'))].join(', ');if(!confirm('This exact PDF (SHA-256 match) is already attached to '+where+'.\n\nAttach the same file here too?'))throw Error('Attachment cancelled');const source=same[0];return TM.Store.createDocument({name:safe,fileName:source.fileName,size:file.size,uploadedBy:actorId,sha256:hash,parentType,parentId})}const disk=crypto.randomUUID()+'.pdf';await TM.FileSystem.writeFile(BASE,disk,file);try{return await TM.Store.createDocument({name:safe,fileName:disk,size:file.size,uploadedBy:actorId,sha256:hash,parentType,parentId})}catch(e){try{await TM.FileSystem.remove(BASE,disk)}catch{}throw e}}
 async function comments(documentId){const base=(await TM.Store.list('documentComment')).filter(x=>!x._corrupt&&x.documentId===documentId),events=(await TM.Store.list('documentCommentEvent')).filter(x=>!x._corrupt&&x.documentId===documentId).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)),map=new Map(base.map(x=>[x.id,{...x}]));for(const e of events){const x=map.get(e.commentId);if(!x)continue;if(e.action==='setStatus')x.status=e.value;if(e.action==='reply'){x.replies=x.replies||[];x.replies.push({actorId:e.actorId,text:e.value,createdAt:e.createdAt})}}return [...map.values()].sort((a,b)=>a.page-b.page||a.createdAt.localeCompare(b.createdAt))}
 async function open(doc,actorId,users){
  if(!window.pdfjsLib)throw Error('Local PDF.js did not load');
  const file=await TM.FileSystem.readFile(BASE,doc.fileName),bytes=new Uint8Array(await file.arrayBuffer());
  const pdf=await pdfjsLib.getDocument({data:bytes,disableWorker:true}).promise;
  const modal=document.createElement('div');modal.className='pdf-review-modal';
  modal.innerHTML='<div class="pdf-review-head"><div><span class="eyebrow">Document Review</span><strong>'+esc(doc.name)+'</strong></div><div class="pdf-review-tools"><button class="secondary" id="pdf-prev-page">‹</button><label>Page <input id="pdf-page" type="number" min="1" max="'+pdf.numPages+'" value="1"> / '+pdf.numPages+'</label><button class="secondary" id="pdf-next-page">›</button><button class="secondary" id="pdf-zoom-out">−</button><span id="pdf-zoom-label">100%</span><button class="secondary" id="pdf-zoom-in">+</button><button class="secondary" id="pdf-place-comment">Place comment</button><button class="secondary" id="pdf-review-close">✕</button></div></div><div class="pdf-review-body"><div class="pdf-stage"><div id="pdf-pages" class="pdf-pages"></div><div id="pdf-comment-compose" class="pdf-comment-compose hidden"><textarea rows="3" placeholder="Comment at this location…"></textarea><div><button id="pdf-comment-save">Add comment</button><button class="secondary" id="pdf-comment-cancel">Cancel</button></div></div></div><aside class="pdf-comments"><div class="pdf-comments-title"><h3>Comments</h3><span id="pdf-comment-count"></span></div><div class="pdf-comment-filters"><button class="secondary active" data-filter="All">All</button><button class="secondary" data-filter="Open">Open</button><button class="secondary" data-filter="Resolved">Resolved</button></div><div id="pdf-comments-list"></div></aside></div>';
  document.body.appendChild(modal);
  const pages=modal.querySelector('#pdf-pages'),stage=modal.querySelector('.pdf-stage'),pageInput=modal.querySelector('#pdf-page'),compose=modal.querySelector('#pdf-comment-compose');
  let placing=false,point=null,filter='All',scale=1,renderToken=0,replyTo=null;

  async function renderPages(){
   const token=++renderToken;pages.innerHTML='<div class="pdf-loading">Rendering '+pdf.numPages+' pages…</div>';
   const frag=document.createDocumentFragment();
   for(let n=1;n<=pdf.numPages;n++){
    if(token!==renderToken)return;
    const p=await pdf.getPage(n),vp=p.getViewport({scale});
    const wrap=document.createElement('section');wrap.className='pdf-page';wrap.dataset.page=n;wrap.style.width=vp.width+'px';wrap.style.height=vp.height+'px';
    const canvas=document.createElement('canvas'),layer=document.createElement('div');canvas.width=Math.ceil(vp.width);canvas.height=Math.ceil(vp.height);canvas.style.width=vp.width+'px';canvas.style.height=vp.height+'px';layer.className='pdf-page-anchors';layer.dataset.page=n;
    wrap.append(canvas,layer);frag.appendChild(wrap);
    await p.render({canvasContext:canvas.getContext('2d'),viewport:vp}).promise;
   }
   if(token!==renderToken)return;pages.innerHTML='';pages.appendChild(frag);await draw();
  }
  function goto(n,commentId=null){n=Math.max(1,Math.min(pdf.numPages,Number(n)||1));pageInput.value=n;const target=pages.querySelector('.pdf-page[data-page="'+n+'"]');target?.scrollIntoView({behavior:'smooth',block:'start'});if(commentId)setTimeout(()=>{const pin=pages.querySelector('.pdf-pin[data-comment="'+commentId+'"]');pin?.classList.add('focus');setTimeout(()=>pin?.classList.remove('focus'),1400)},350)}
  async function draw(){
   const rows=await comments(doc.id),shown=filter==='All'?rows:rows.filter(x=>x.status===filter);modal.querySelector('#pdf-comment-count').textContent=rows.filter(x=>x.status==='Open').length+' open · '+rows.length+' total';
   pages.querySelectorAll('.pdf-page-anchors').forEach(layer=>{const n=Number(layer.dataset.page);layer.classList.toggle('placing',placing);layer.innerHTML=shown.filter(x=>x.page===n).map(x=>'<button class="pdf-pin '+(x.status==='Resolved'?'resolved':'')+'" data-comment="'+x.id+'" style="left:'+(Math.max(0,Math.min(1,x.x))*100)+'%;top:'+(Math.max(0,Math.min(1,x.y))*100)+'%" title="'+esc(x.text)+'">'+(rows.indexOf(x)+1)+'</button>').join('')});
   modal.querySelector('#pdf-comments-list').innerHTML=shown.length?shown.map(x=>'<button class="pdf-comment-row" data-id="'+x.id+'" data-page="'+x.page+'"><span class="pdf-comment-number">'+(rows.indexOf(x)+1)+'</span><div><strong>Page '+x.page+'</strong><p>'+esc(x.text)+'</p><small>'+esc(users.get(x.authorId)||x.authorId)+' · '+esc(String(x.createdAt).slice(0,16).replace('T',' '))+' · '+esc(x.status)+'</small>'+(x.replies?.length?'<div class="pdf-replies">'+x.replies.map(r=>'<div><b>'+esc(users.get(r.actorId)||r.actorId)+'</b> '+esc(r.text)+'</div>').join('')+'</div>':'')+'</div><span class="pdf-comment-status">'+(x.status==='Resolved'?'✓':'○')+'</span><span class="pdf-comment-actions"><span class="secondary pdf-status-toggle" data-id="'+x.id+'" data-status="'+x.status+'">'+(x.status==='Resolved'?'Reopen':'Resolve')+'</span><span class="secondary pdf-reply" data-id="'+x.id+'">Reply</span></span></button>').join(''):'<p class="muted">No comments yet. Choose Place comment, then click the PDF page.</p>';
   modal.querySelectorAll('.pdf-comment-row').forEach(b=>b.onclick=()=>goto(b.dataset.page,b.dataset.id));
   modal.querySelectorAll('.pdf-reply').forEach(b=>b.onclick=e=>{e.stopPropagation();replyTo=b.dataset.id;const row=b.closest('.pdf-comment-row');row.querySelector('.pdf-inline-reply')?.remove();const box=document.createElement('div');box.className='pdf-inline-reply';box.innerHTML='<textarea rows="2" placeholder="Write a reply…"></textarea><div><button class="pdf-inline-reply-save">Reply</button><button class="secondary pdf-inline-reply-cancel">Cancel</button></div>';row.appendChild(box);const ta=box.querySelector('textarea');ta.focus();box.onclick=x=>x.stopPropagation();box.querySelector('.pdf-inline-reply-cancel').onclick=()=>{replyTo=null;box.remove()};box.querySelector('.pdf-inline-reply-save').onclick=async()=>{const value=ta.value.trim();if(!value)return;await TM.Store.addDocumentCommentEvent({commentId:replyTo,documentId:doc.id,actorId,action:'reply',value});replyTo=null;await draw()};ta.onkeydown=e=>{if(e.key==='Escape'){replyTo=null;box.remove()}if((e.ctrlKey||e.metaKey)&&e.key==='Enter')box.querySelector('.pdf-inline-reply-save').click()}});
   modal.querySelectorAll('.pdf-status-toggle').forEach(b=>b.onclick=async e=>{e.stopPropagation();await TM.Store.addDocumentCommentEvent({commentId:b.dataset.id,documentId:doc.id,actorId,action:'setStatus',value:b.dataset.status==='Resolved'?'Open':'Resolved'});await draw()});
   modal.querySelectorAll('.pdf-pin').forEach(b=>b.onclick=e=>{e.stopPropagation();const row=modal.querySelector('.pdf-comment-row[data-id="'+b.dataset.comment+'"]');row?.scrollIntoView({behavior:'smooth',block:'center'});row?.classList.add('focus');setTimeout(()=>row?.classList.remove('focus'),1200)});
  }
  pages.onclick=e=>{const layer=e.target.closest('.pdf-page-anchors');if(!placing||!layer||e.target.closest('.pdf-pin'))return;const r=layer.getBoundingClientRect();point={page:Number(layer.dataset.page),x:Math.max(0,Math.min(1,(e.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(e.clientY-r.top)/r.height))};const sr=stage.getBoundingClientRect();compose.style.left=Math.min(stage.clientWidth-330,Math.max(8,e.clientX-sr.left+stage.scrollLeft))+'px';compose.style.top=Math.max(8,e.clientY-sr.top+stage.scrollTop)+'px';compose.classList.remove('hidden');compose.querySelector('textarea').focus()};
  pageInput.onchange=()=>goto(pageInput.value);modal.querySelector('#pdf-prev-page').onclick=()=>goto(Number(pageInput.value)-1);modal.querySelector('#pdf-next-page').onclick=()=>goto(Number(pageInput.value)+1);
  const zoom=async delta=>{scale=Math.max(.5,Math.min(2.5,scale+delta));modal.querySelector('#pdf-zoom-label').textContent=Math.round(scale*100)+'%';await renderPages();goto(pageInput.value)};
  modal.querySelector('#pdf-zoom-out').onclick=()=>zoom(-.15);modal.querySelector('#pdf-zoom-in').onclick=()=>zoom(.15);
  modal.querySelector('#pdf-place-comment').onclick=async()=>{placing=!placing;modal.querySelector('#pdf-place-comment').classList.toggle('active',placing);await draw()};
  modal.querySelector('#pdf-comment-cancel').onclick=()=>{compose.classList.add('hidden');point=null};
  modal.querySelector('#pdf-comment-save').onclick=async()=>{const text=compose.querySelector('textarea').value.trim();if(!point||!text)return;await TM.Store.addDocumentComment({documentId:doc.id,authorId:actorId,page:point.page,x:point.x,y:point.y,text});compose.querySelector('textarea').value='';compose.classList.add('hidden');placing=false;point=null;modal.querySelector('#pdf-place-comment').classList.remove('active');await draw()};
  modal.querySelectorAll('.pdf-comment-filters button').forEach(b=>b.onclick=async()=>{filter=b.dataset.filter;modal.querySelectorAll('.pdf-comment-filters button').forEach(x=>x.classList.toggle('active',x===b));await draw()});
  modal.querySelector('#pdf-review-close').onclick=()=>{renderToken++;modal.remove();pdf.destroy()};
  await renderPages();
 }
 async function linkedDocuments(parentType,parentId){return (await list()).filter(x=>x.parentType===parentType&&x.parentId===parentId&&x.status!=='Archived')}
 async function attachmentPanel(parentType,parentId){const docs=await linkedDocuments(parentType,parentId),imgs=(await TM.Store.list('commentAttachment')).filter(x=>!x._corrupt&&x.parentType===parentType&&x.parentId===parentId);return '<span class="comment-attachment-tools"><label class="editor-attach-btn" title="Attach PDF" aria-label="Attach PDF">📎<input class="record-pdf-upload" type="file" accept="application/pdf,.pdf" hidden></label><label class="editor-attach-btn" title="Attach image" aria-label="Attach image">🖼️<input class="record-image-upload" type="file" accept="image/png,image/jpeg,image/webp,image/gif" hidden></label>'+(docs.length||imgs.length?'<span class="attachment-count">'+(docs.length+imgs.length)+'</span>':'')+'</span>'+(docs.length||imgs.length?'<div class="inline-attachments">'+docs.map(x=>'<button type="button" class="inline-attachment record-pdf-review" data-doc="'+x.id+'" data-attachment-kind="pdf" data-attachment-name="'+esc(x.name)+'">📄 '+esc(x.name)+'</button>').join('')+imgs.map(x=>'<button type="button" class="inline-attachment record-image-view" data-file="'+x.fileName+'" data-attachment-kind="image" data-attachment-name="'+esc(x.name)+'" data-attachment-mime="'+esc(x.mimeType||'image/*')+'">🖼 '+esc(x.name)+'</button>').join('')+'</div>':'')}
 async function bindAttachmentPanel(parentType,parentId,actorId,onChanged){const root=document.querySelector('.rich-editor');if(!root)return;const pdf=root.querySelector('.record-pdf-upload'),image=root.querySelector('.record-image-upload');if(pdf)pdf.onchange=async()=>{const file=pdf.files?.[0];if(!file)return;try{pdf.disabled=true;await upload(file,actorId,parentType,parentId);if(onChanged)await onChanged()}catch(e){alert(e.message)}finally{pdf.disabled=false}};if(image)image.onchange=async()=>{const file=image.files?.[0];if(!file)return;if(!/^image\/(png|jpeg|webp|gif)$/.test(file.type))return alert('Select a PNG, JPEG, WebP or GIF image');if(file.size>10*1024*1024)return alert('Image must be 10 MB or smaller');const ext=(file.name.split('.').pop()||'img').replace(/[^a-z0-9]/gi,'').toLowerCase(),disk=crypto.randomUUID()+'.'+ext,safe=file.name.replace(/[^a-zA-Z0-9._ -]/g,'_');let wrote=false;try{image.disabled=true;await TM.FileSystem.createDirectory(['Task-Management-Data','Attachments','Files']);await TM.FileSystem.writeFile(['Task-Management-Data','Attachments','Files'],disk,file);wrote=true;await TM.Store.addCommentAttachment({parentType,parentId,uploadedBy:actorId,name:safe,fileName:disk,size:file.size,mimeType:file.type});if(onChanged)await onChanged()}catch(e){if(wrote)try{await TM.FileSystem.remove(['Task-Management-Data','Attachments','Files'],disk)}catch{}alert(e.message)}finally{image.disabled=false}};root.querySelectorAll('.record-pdf-review').forEach(b=>b.onclick=async()=>{const doc=(await list()).find(x=>x.id===b.dataset.doc);if(!doc)return;const users=new Map();for(const u of (await TM.Store.list('user')).filter(x=>!x._corrupt)){const s=await TM.Identity.userState(u.id);users.set(u.id,s.displayName||s.username||u.id)}await open(doc,actorId,users)});root.querySelectorAll('.record-image-view').forEach(b=>b.onclick=async()=>{try{const f=await TM.FileSystem.readFile(['Task-Management-Data','Attachments','Files'],b.dataset.file),url=URL.createObjectURL(f);const modal=document.createElement('div');modal.className='image-preview-modal';modal.innerHTML='<button class="image-preview-close">✕</button><img alt="Attached image">';modal.querySelector('img').src=url;modal.querySelector('.image-preview-close').onclick=()=>{URL.revokeObjectURL(url);modal.remove()};modal.onclick=e=>{if(e.target===modal){URL.revokeObjectURL(url);modal.remove()}};document.body.appendChild(modal)}catch(e){alert(e.message)}})}

 function selectedAttachments(root=document.querySelector('.rich-editor')){if(!root)return[];return [...root.querySelectorAll('.inline-attachment')].map(b=>b.dataset.attachmentKind==='pdf'?{kind:'pdf',documentId:b.dataset.doc,name:b.dataset.attachmentName||b.textContent.trim()}:{kind:'image',fileName:b.dataset.file,name:b.dataset.attachmentName||b.textContent.trim(),mimeType:b.dataset.attachmentMime||'image/*'}).filter(x=>x.name)}
 function commentAttachmentsHtml(items=[]){return Array.isArray(items)&&items.length?'<div class="comment-file-list">'+items.map(x=>x.kind==='pdf'?'<button type="button" class="inline-attachment comment-pdf-attachment" data-doc="'+esc(x.documentId)+'">📄 '+esc(x.name)+'</button>':'<button type="button" class="inline-attachment comment-image-attachment" data-file="'+esc(x.fileName)+'">🖼 '+esc(x.name)+'</button>').join('')+'</div>':''}
 async function openImageFile(fileName){const f=await TM.FileSystem.readFile(['Task-Management-Data','Attachments','Files'],fileName),url=URL.createObjectURL(f),modal=document.createElement('div');modal.className='image-preview-modal';modal.innerHTML='<button class="image-preview-close">✕</button><img alt="Attached image">';modal.querySelector('img').src=url;const close=()=>{URL.revokeObjectURL(url);modal.remove()};modal.querySelector('.image-preview-close').onclick=close;modal.onclick=e=>{if(e.target===modal)close()};document.body.appendChild(modal)}
 async function bindCommentAttachments(root=document,actorId){root.querySelectorAll('.comment-pdf-attachment').forEach(b=>b.onclick=async()=>{const doc=(await list()).find(x=>x.id===b.dataset.doc);if(!doc)return;const users=new Map();for(const u of (await TM.Store.list('user')).filter(x=>!x._corrupt)){const s=await TM.Identity.userState(u.id);users.set(u.id,s.displayName||s.username||u.id)}await open(doc,actorId,users)});root.querySelectorAll('.comment-image-attachment').forEach(b=>b.onclick=()=>openImageFile(b.dataset.file).catch(e=>alert(e.message)))}
 async function linkedComments(parentType,parentId){const docs=(await list()).filter(x=>x.parentType===parentType&&x.parentId===parentId&&x.status!=='Archived'),out=[];for(const d of docs){for(const x of await comments(d.id))out.push({...x,documentId:d.id,documentName:d.name})}return out.sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)))}
 async function openLinkedComment(documentId,commentId,actorId){const doc=(await list()).find(x=>x.id===documentId);if(!doc)throw Error('Document not found');const users=new Map();for(const u of (await TM.Store.list('user')).filter(x=>!x._corrupt)){const s=await TM.Identity.userState(u.id);users.set(u.id,s.displayName||s.username||u.id)}await open(doc,actorId,users);const row=(await comments(documentId)).find(x=>x.id===commentId);if(row)setTimeout(()=>{const target=document.querySelector('.pdf-comment-row[data-id="'+commentId+'"]');target?.click()},250)}
 async function render(actorId){const allRows=await list(),showArchived=sessionStorage.getItem('tm-documents-show-archived')==='1',rows=allRows.filter(x=>showArchived||x.status!=='Archived'),allComments=await TM.Store.list('documentComment'),commentCounts=new Map();for(const x of allComments.filter(x=>!x._corrupt))commentCounts.set(x.documentId,(commentCounts.get(x.documentId)||0)+1);return '<div class="top"><div><span class="eyebrow">Shared Workspace</span><h1>Document Review</h1><p class="muted">Attach PDFs and review them with page/location comments.</p></div><div class="document-page-actions"><button class="secondary" id="document-toggle-archived">'+(showArchived?'Hide Archived':'Show Archived')+'</button><label class="button-like">+ Attach PDF<input id="document-upload" type="file" accept="application/pdf,.pdf" hidden></label></div></div><div class="document-grid">'+(rows.map(x=>'<article class="card document-card" data-id="'+x.id+'"><span class="document-icon">PDF</span><div><h3>'+esc(x.name)+'</h3><p>'+Math.max(1,Math.round((x.size||0)/1024))+' KB · '+(commentCounts.get(x.id)||0)+' comments</p><small>'+esc(String(x.createdAt).slice(0,16).replace('T',' '))+'</small></div><div class="document-actions"><button class="secondary document-open">Review</button><button class="secondary document-archive">'+(x.status==='Archived'?'Restore':'Archive')+'</button></div></article>').join('')||'<div class="card"><h3>No PDFs attached</h3><p class="muted">Attach a PDF to start a document review.</p></div>')+'</div>'}
 async function bind(actorId,onRender,onMessage){const users=new Map();for(const u of (await TM.Store.list('user')).filter(x=>!x._corrupt))users.set(u.id,u.displayName||u.username);const toggle=document.querySelector('#document-toggle-archived');if(toggle)toggle.onclick=async()=>{sessionStorage.setItem('tm-documents-show-archived',sessionStorage.getItem('tm-documents-show-archived')==='1'?'0':'1');await onRender()};const input=document.querySelector('#document-upload');input.onchange=async()=>{try{input.disabled=true;await upload(input.files[0],actorId);onMessage('PDF attached.',true);await onRender()}catch(e){onMessage(e.message)}finally{input.disabled=false}};document.querySelectorAll('.document-card').forEach(card=>{card.querySelector('.document-open').onclick=async()=>{try{await open(await TM.Store.get('document',card.dataset.id),actorId,users)}catch(e){onMessage(e.message)}};card.querySelector('.document-archive').onclick=async()=>{const d=await TM.Store.get('document',card.dataset.id),events=(await TM.Store.list('documentEvent')).filter(x=>!x._corrupt&&x.documentId===card.dataset.id).sort((a,b)=>a.createdAt.localeCompare(b.createdAt));let archived=false;for(const e of events){if(e.action==='archive')archived=true;if(e.action==='restore')archived=false}const action=archived?'restore':'archive';if(!confirm((archived?'Restore':'Archive')+' this document? The PDF and review history will be preserved.'))return;try{await TM.Store.addDocumentEvent({documentId:card.dataset.id,actorId,action});onMessage(archived?'Document restored.':'Document archived.',true);await onRender()}catch(e){onMessage(e.message)}}})}
 return{list,upload,comments,linkedDocuments,attachmentPanel,bindAttachmentPanel,selectedAttachments,commentAttachmentsHtml,bindCommentAttachments,linkedComments,openLinkedComment,render,bind,open};
})();