(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function page(){const root=document.querySelector('#page-content');document.querySelectorAll('.nav button[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page==='dummy-data'));root.innerHTML=`<div class="page-head"><div><h1>Dummy Data Lab</h1><p class="muted">Temporary development tool. Import JSON test data into this browser's IndexedDB workspace.</p></div><span class="badge">TEMPORARY</span></div><section class="card"><h2>Import dummy workspace</h2><p>Supported sections: <code>groups</code>, <code>projects</code>, and <code>tasks</code>. Existing workspace records are preserved.</p><input id="dummy-file" type="file" accept="application/json,.json"><div id="dummy-preview" class="muted" style="margin-top:12px">Select a JSON file to validate it.</div><div class="modal-actions"><button id="dummy-import" disabled>Import dummy data</button></div><div id="dummy-msg" class="hidden"></div></section><section class="card"><h2>Expected JSON shape</h2><pre>{
  "groups": [{"name":"Cyber Security"}],
  "projects": [{"name":"SOC Upgrade","group":"Cyber Security"}],
  "tasks": [{"title":"Review alerts","group":"Cyber Security","project":"SOC Upgrade","priority":"High","status":"In Progress","expectedFinish":"2026-09-20T12:00:00"}]
}</pre></section>`;let parsed=null;const input=document.querySelector('#dummy-file'),preview=document.querySelector('#dummy-preview'),btn=document.querySelector('#dummy-import'),msg=document.querySelector('#dummy-msg');input.onchange=async()=>{parsed=null;btn.disabled=true;try{const f=input.files[0];if(!f)return;const x=JSON.parse(await f.text());if(!x||typeof x!=='object')throw Error('JSON root must be an object.');for(const k of ['groups','projects','tasks'])if(x[k]!==undefined&&!Array.isArray(x[k]))throw Error(`${k} must be an array.`);parsed=x;preview.innerHTML=`Ready: <strong>${x.groups?.length||0}</strong> groups · <strong>${x.projects?.length||0}</strong> projects · <strong>${x.tasks?.length||0}</strong> tasks`;btn.disabled=false}catch(e){preview.textContent='Invalid dummy-data file: '+e.message}};btn.onclick=async()=>{if(!parsed)return;btn.disabled=true;btn.textContent='Importing…';try{const result=await importData(parsed);msg.textContent=`Imported ${result.groups} groups, ${result.projects} projects and ${result.tasks} tasks.`;msg.className='success';btn.textContent='Import dummy data'}catch(e){msg.textContent=e.message;msg.className='error';btn.disabled=false;btn.textContent='Import dummy data'}}}
async function importData(data){const actor=await TM.Auth.currentUser(),existingGroups=await TM.DB.getAll('groups'),groupMap=new Map(existingGroups.map(g=>[g.name.toLowerCase(),g]));let gc=0,pc=0,tc=0;for(const x of data.groups||[]){const name=String(x.name||'').trim();if(!name||groupMap.has(name.toLowerCase()))continue;const id=await TM.DB.add('groups',{name,description:String(x.description||''),enabled:true,createdAt:new Date().toISOString(),updatedAt:new Date().toISOString()});const row=await TM.DB.get('groups',id);groupMap.set(name.toLowerCase(),row);gc++}const existingProjects=await TM.DB.getAll('projects'),projectMap=new Map(existingProjects.map(p=>[p.name.toLowerCase(),p]));for(const x of data.projects||[]){const name=String(x.name||'').trim();if(!name||projectMap.has(name.toLowerCase()))continue;const g=groupMap.get(String(x.group||'').toLowerCase());const id=await TM.Work.createProject({name,description:x.description||'',groupId:g?.id||null,expectedFinish:x.expectedFinish||''},actor);projectMap.set(name.toLowerCase(),await TM.DB.get('projects',id));pc++}for(const x of data.tasks||[]){const g=groupMap.get(String(x.group||'').toLowerCase()),p=projectMap.get(String(x.project||'').toLowerCase());const due=x.expectedFinish||new Date(Date.now()+7*86400000).toISOString();const id=await TM.Work.createTask({title:x.title||'Dummy task',description:x.description||'',groupId:g?.id||null,projectId:p?.id||null,priority:x.priority||'Normal',expectedFinish:due},actor);if(x.status==='In Progress'||x.status==='Finished')await TM.Work.changeTaskStatus(id,'In Progress',actor);if(x.status==='Finished')await TM.Work.changeTaskStatus(id,'Finished',actor);if(x.comment)await TM.Work.comment(id,String(x.comment),actor,{attachments:[]});tc++}await TM.DB.audit('DUMMY_DATA_IMPORTED','system',null,{groups:gc,projects:pc,tasks:tc});return{groups:gc,projects:pc,tasks:tc}}
window.TM=window.TM||{};TM.DummyData={page,importData};
})();