window.TM=window.TM||{};
TM.Identity=(()=>{
 async function events(type,key,value){return(await TM.Store.list(type)).filter(e=>!e._corrupt&&e[key]===value).sort((a,b)=>a.createdAt.localeCompare(b.createdAt)||a.id.localeCompare(b.id))}
 async function userState(id){const base=await TM.Store.get('user',id),state={...base};for(const e of await events('userEvent','userId',id)){if(e.action==='setEnabled')state.enabled=!!e.value;if(e.action==='setDisplayName')state.displayName=e.value}return state}
 async function groupState(id){const base=await TM.Store.get('group',id),state={...base};for(const e of await events('groupEvent','groupId',id)){if(e.action==='setName')state.name=e.value;if(e.action==='setDescription')state.description=e.value;if(e.action==='setEnabled')state.enabled=!!e.value}return state}\n async function setGroupDetails(groupId,{name,description},actorId){name=String(name||'').trim();if(!name)throw Error('group name required');await TM.Store.get('group',groupId);await TM.Store.create('groupEvent',{groupId,action:'setName',value:name,actorId});return TM.Store.create('groupEvent',{groupId,action:'setDescription',value:String(description||'').trim(),actorId})}\n async function setGroupEnabled(groupId,value,actorId){await TM.Store.get('group',groupId);return TM.Store.create('groupEvent',{groupId,action:'setEnabled',value:!!value,actorId})}\n async function membershipState(m){let enabled=m.enabled!==false;for(const e of await events('membershipEvent','membershipId',m.id))if(e.action==='setEnabled')enabled=!!e.value;return{...m,enabled}}
 async function adminRole(){return(await TM.Store.list('role')).find(r=>!r._corrupt&&r.systemKey==='administrator')}
 async function activeAdmins(){const role=await adminRole(),ms=await TM.Store.list('membership'),ids=new Set();if(!role)return[];for(const m of ms){if(m._corrupt||m.roleId!==role.id)continue;const x=await membershipState(m);if(!x.enabled)continue;const u=await userState(m.userId);if(u.enabled)ids.add(u.id)}return[...ids]}
 async function setUserEnabled(userId,value,actorId){const current=await userState(userId);if(current.enabled===!!value)return null;if(!value&&(await activeAdmins()).includes(userId)&&(await activeAdmins()).length<=1)throw Error('Cannot disable the final active Administrator');return TM.Store.create('userEvent',{userId,action:'setEnabled',value:!!value,actorId})}
 async function setDisplayName(userId,value,actorId){if(!String(value).trim())throw Error('displayName required');return TM.Store.create('userEvent',{userId,action:'setDisplayName',value:String(value).trim(),actorId})}
 async function setMembershipEnabled(membershipId,value,actorId){const m=await TM.Store.get('membership',membershipId),role=await adminRole();if(!value&&role&&m.roleId===role.id){const u=await userState(m.userId);if(u.enabled&&(await activeAdmins()).length<=1)throw Error('Cannot remove the final active Administrator membership')}return TM.Store.create('membershipEvent',{membershipId,action:'setEnabled',value:!!value,actorId})}
 return{userState,groupState,membershipState,activeAdmins,setUserEnabled,setDisplayName,setMembershipEnabled,setGroupDetails,setGroupEnabled};
})();