(()=>{
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function create(userId,type,title,message,entityType='',entityId=null,actorUserId=null){userId=Number(userId)||null;if(!userId||userId===Number(actorUserId))return null;const id=await TM.DB.add('notifications',{userId,type,title:String(title||'Notification'),message:String(message||''),entityType,entityId:Number(entityId)||null,actorUserId:Number(actorUserId)||null,read:false,createdAt:new Date().toISOString(),readAt:null});refresh();return id}
async function forUser(userId){return (await TM.DB.allByIndex('notifications','userId',Number(userId))).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
async function unread(userId){return (await forUser(userId)).filter(n=>!n.read)}
async function markRead(id){const n=await TM.DB.get('notifications',Number(id));if(n&&!n.read){n.read=true;n.readAt=new Date().toISOString();await TM.DB.put('notifications',n)}await refresh()}
async function markAll(){const u=await TM.Auth.currentUser();if(!u)return;for(const n of await unread(u.id)){n.read=true;n.readAt=new Date().toISOString();await TM.DB.put('notifications',n)}await refresh()}
async function openEntity(n){await markRead(n.id);close();if(n.entityType==='task'&&n.entityId){if(TM.TaskDetailV2?.render)return TM.TaskDetailV2.render(n.entityId);if(TM.Stage03?.taskDetail)return TM.Stage03.taskDetail(n.entityId)}if(n.entityType==='project'&&TM.Router)return TM.Router.route('projects');if(n.entityType==='ticket'&&TM.Router)return TM.Router.route('tickets')}
function close(){document.querySelector('#notification-panel')?.remove()}
async function toggle(){if(document.querySelector('#notification-panel'))return close();const u=await TM.Auth.currentUser();if(!u)return;const rows=await forUser(u.id),panel=document.createElement('div');panel.id='notification-panel';panel.className='notification-panel';panel.innerHTML=`<div class="notification-head"><strong>Notifications</strong><button id="notification-read-all" class="secondary">Mark all read</button></div><div class="notification-list">${rows.length?rows.slice(0,50).map(n=>`<button class="notification-item ${n.read?'':'unread'}" data-notification="${n.id}"><span class="notification-dot"></span><span><strong>${esc(n.title)}</strong><small>${esc(n.message)}</small><time>${new Date(n.createdAt).toLocaleString()}</time></span></button>`).join(''):'<p class="muted notification-empty">No notifications.</p>'}</div>`;document.body.appendChild(panel);panel.querySelector('#notification-read-all').onclick=markAll;panel.querySelectorAll('[data-notification]').forEach(b=>b.onclick=()=>openEntity(rows.find(n=>n.id===Number(b.dataset.notification))))}
async function refresh(){const bell=document.querySelector('#notification-bell'),badge=document.querySelector('#notification-count');if(!bell||!badge)return;const u=await TM.Auth.currentUser();if(!u){badge.hidden=true;return}const n=(await unread(u.id)).length;badge.textContent=n>99?'99+':String(n);badge.hidden=!n;bell.title=n?`${n} unread notification${n===1?'':'s'}`:'Notifications'}
function init(){const bell=document.querySelector('#notification-bell');if(!bell)return;bell.onclick=e=>{e.stopPropagation();toggle()};document.addEventListener('click',e=>{const p=document.querySelector('#notification-panel');if(p&&!p.contains(e.target)&&!bell.contains(e.target))close()});setInterval(refresh,5000);refresh()}
window.TM=window.TM||{};TM.Notifications={create,forUser,unread,markRead,markAll,refresh,toggle,init};document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();