window.TM=window.TM||{};
TM.Personal=(()=>{
 const esc=v=>{const d=document.createElement('div');d.textContent=String(v??'');return d.innerHTML};
 const tabs=[['notes','Notes'],['reminders','Reminders'],['phonebook','Phone Book'],['emailbook','Email Book'],['bookmarks','Important URLs'],['profile','My Profile']];
 const cfg={
 notes:{title:'Notes',fields:[['title','Title','text'],['body','Note','textarea'],['tags','Tags','text']]},
 reminders:{title:'Reminders',fields:[['title','Title','text'],['details','Details','textarea'],['remindAt','Date / Time','datetime-local'],['priority','Priority','select']]},
 phonebook:{title:'Phone Book',fields:[['name','Name','text'],['organization','Organization','text'],['phone','Phone / Mobile','text'],['extension','Extension','text'],['notes','Notes','textarea']]},
 emailbook:{title:'Email Book',fields:[['name','Name','text'],['organization','Organization','text'],['email','Email','email'],['notes','Notes','textarea']]},
 bookmarks:{title:'Important URLs',fields:[['name','Name','text'],['url','URL','url'],['category','Category','text'],['username','Username','text'],['description','Description','textarea']]}
 };
 const buttons=active=>'<div class="personal-tabs">'+tabs.map(x=>'<button class="secondary personal-tab'+(active===x[0]?' active':'')+'" data-personal="'+x[0]+'">'+x[1]+'</button>').join('')+'</div>';
 function fields(c,r={}){return c.fields.map(([n,l,t])=>{if(t==='textarea')return '<label>'+l+'<textarea name="'+n+'" rows="4">'+esc(r[n]||'')+'</textarea></label>';if(t==='select')return '<label>'+l+'<select name="'+n+'">'+['Low','Normal','High','Critical'].map(x=>'<option'+(r[n]===x?' selected':'')+'>'+x+'</option>').join('')+'</select></label>';return '<label>'+l+'<input name="'+n+'" type="'+t+'" value="'+esc(r[n]||'')+'"></label>'}).join('')}
 async function render(userId,active='home'){const counts=await TM.PersonalDB.counts(userId);if(active==='home')return '<div class="top"><div><h1>My Workspace</h1><p class="muted">Private data stored only in this Chrome browser.</p></div></div>'+buttons('')+'<div class="dashboard-stats">'+[['Notes',counts.notes],['Reminders',counts.reminders],['Phone Book',counts.phonebook],['Email Book',counts.emailbook],['Important URLs',counts.bookmarks]].map(x=>'<div class="card"><span class="eyebrow">'+x[0]+'</span><div class="metric">'+x[1]+'</div></div>').join('')+'</div>';if(active==='profile')return profile(userId);const c=cfg[active],rows=await TM.PersonalDB.list(active,userId);return '<div class="top"><div><h1>My Workspace</h1><p class="muted">Private browser-local information.</p></div><button id="personal-add">+ Add '+c.title+'</button></div>'+buttons(active)+'<div id="personal-editor"></div><div class="card"><table class="table"><tr>'+c.fields.slice(0,3).map(x=>'<th>'+x[1]+'</th>').join('')+'<th>Updated</th><th>Action</th></tr>'+rows.map(r=>'<tr>'+c.fields.slice(0,3).map(x=>'<td>'+esc(r[x[0]]||'—')+'</td>').join('')+'<td>'+esc(String(r.updatedAt||'').slice(0,16).replace('T',' '))+'</td><td><button class="secondary personal-edit" data-id="'+r.id+'">Edit</button> <button class="secondary personal-delete" data-id="'+r.id+'">Delete</button></td></tr>').join('')+'</table></div>'}
 async function profile(userId){const p=await TM.PersonalDB.profile(userId)||{};return '<div class="top"><div><h1>My Workspace</h1><p class="muted">Shared account identity stays in JSON. The fields below stay in this browser.</p></div></div>'+buttons('profile')+'<div class="card"><h2>Personal Information</h2><form id="personal-profile"><div class="form-row"><label>Personal phone<input name="phone" value="'+esc(p.phone||'')+'"></label><label>Personal email<input type="email" name="email" value="'+esc(p.email||'')+'"></label></div><label>Location / Address<input name="address" value="'+esc(p.address||'')+'"></label><label>Personal notes<textarea name="notes" rows="4">'+esc(p.notes||'')+'</textarea></label><button>Save Personal Information</button></form></div><div class="card"><h2>Change Password</h2><p class="muted">Authentication remains in the shared JSON datastore.</p><form id="change-password"><label>Current password<input type="password" name="current" required></label><label>New password<input type="password" name="next" minlength="12" required></label><label>Confirm new password<input type="password" name="confirm" minlength="12" required></label><button>Change Password</button></form></div>'}
 async function bind(userId,active,onRender,onMessage){document.querySelectorAll('.personal-tab').forEach(b=>b.onclick=()=>onRender(b.dataset.personal));if(active==='home')return;if(active==='profile'){document.querySelector('#personal-profile').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);await TM.PersonalDB.saveProfile(userId,{phone:f.get('phone'),email:f.get('email'),address:f.get('address'),notes:f.get('notes')});onMessage('Personal information saved.',true)};document.querySelector('#change-password').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target);if(f.get('next')!==f.get('confirm'))return onMessage('New passwords do not match');try{await TM.Auth.changePassword(userId,f.get('current'),f.get('next'));e.target.reset();onMessage('Password changed.',true)}catch(x){onMessage(x.message)}};return}const c=cfg[active],editor=document.querySelector('#personal-editor');async function form(r={}){editor.innerHTML='<div class="card"><h2>'+(r.id?'Edit ':'Add ')+c.title+'</h2><form id="personal-form">'+fields(c,r)+'<button>Save</button> <button type="button" class="secondary" id="personal-cancel">Cancel</button></form></div>';document.querySelector('#personal-cancel').onclick=()=>editor.innerHTML='';document.querySelector('#personal-form').onsubmit=async e=>{e.preventDefault();const f=new FormData(e.target),v={id:r.id};for(const [n] of c.fields)v[n]=f.get(n)||'';await TM.PersonalDB.put(active,userId,v);onMessage('Personal record saved.',true);await onRender(active)}}document.querySelector('#personal-add').onclick=()=>form();document.querySelectorAll('.personal-edit').forEach(b=>b.onclick=async()=>form(await TM.PersonalDB.get(active,b.dataset.id)));document.querySelectorAll('.personal-delete').forEach(b=>b.onclick=async()=>{if(confirm('Delete this personal record?')){await TM.PersonalDB.remove(active,b.dataset.id,userId);await onRender(active)}})}
 return{render,bind};
})();