window.TM=window.TM||{};
TM.Projects=(()=>{
 const clean=v=>String(v??'').trim();
 async function state(id){const base=await TM.Store.get('project',id),s={...base};const events=(await TM.Store.list('projectEvent')).filter(e=>!e._corrupt&&e.projectId===id).sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt))||a.id.localeCompare(b.id));for(const e of events){if(e.action==='setName')s.name=e.value;if(e.action==='setDescription')s.description=e.value;if(e.action==='setStatus')s.status=e.value;if(e.action==='setGroup')s.groupId=e.value||null}return s}
 async function list(){const out=[];for(const p of (await TM.Store.list('project')).filter(x=>!x._corrupt))out.push(await state(p.id));return out}
 async function create(actorId,{name,description='',groupId=null}){name=clean(name);if(!name)throw Error('Project name required');if(!await TM.Auth.can(actorId,'tasks.create'))throw Error('Permission denied');const existing=await list();if(existing.some(p=>p.status!=='Archived'&&clean(p.name).toLowerCase()===name.toLowerCase()))throw Error('Project name already exists');return TM.Store.createProject({name,description:clean(description),ownerId:actorId,groupId,status:'Active'})}
 async function update(actorId,id,{name,description,groupId}){if(!await TM.Auth.can(actorId,'tasks.edit'))throw Error('Permission denied');const p=await state(id);if(name!==undefined&&clean(name)!==p.name)await TM.Store.addProjectEvent({projectId:id,action:'setName',value:clean(name),actorId});if(description!==undefined&&clean(description)!==p.description)await TM.Store.addProjectEvent({projectId:id,action:'setDescription',value:clean(description),actorId});if(groupId!==undefined&&groupId!==p.groupId)await TM.Store.addProjectEvent({projectId:id,action:'setGroup',value:groupId||null,actorId});return state(id)}
 async function setStatus(actorId,id,status){if(!await TM.Auth.can(actorId,'tasks.edit'))throw Error('Permission denied');if(!['Active','On Hold','Completed','Archived'].includes(status))throw Error('Invalid project status');await TM.Store.addProjectEvent({projectId:id,action:'setStatus',value:status,actorId});return state(id)}
 async function members(id){const rows=(await TM.Store.list('projectMember')).filter(x=>!x._corrupt&&x.projectId===id);return rows.filter(x=>x.enabled!==false)}
 async function addMember(actorId,projectId,userId,role='member'){if(!await TM.Auth.can(actorId,'tasks.delegate'))throw Error('Permission denied');const rows=await members(projectId);if(rows.some(x=>x.userId===userId))throw Error('User already belongs to project');return TM.Store.addProjectMember({projectId,userId,role,actorId})}
 return{state,list,create,update,setStatus,members,addMember};
})();
