window.TM=window.TM||{};
TM.Projects=(()=>{
 const clean=v=>String(v??'').trim();
 async function state(id){const base=await TM.Store.get('project',id),s={...base};const events=(await TM.Store.list('projectEvent')).filter(e=>!e._corrupt&&e.projectId===id).sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt))||a.id.localeCompare(b.id));for(const e of events){if(e.action==='setName')s.name=e.value;if(e.action==='setDescription')s.description=e.value;if(e.action==='setStatus')s.status=e.value}return s}
 async function list(){const out=[];for(const p of (await TM.Store.list('project')).filter(x=>!x._corrupt))out.push(await state(p.id));return out}
 async function groupState(row){const s={...row};const es=(await TM.Store.list('projectGroupEvent')).filter(e=>!e._corrupt&&e.projectGroupId===row.id).sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt))||a.id.localeCompare(b.id));for(const e of es)if(e.action==='setEnabled')s.enabled=!!e.value;return s}
 async function groups(id){const rows=[];for(const x of (await TM.Store.list('projectGroup')).filter(x=>!x._corrupt&&x.projectId===id)){const s=await groupState(x);if(s.enabled!==false)rows.push(s)}const legacy=(await state(id)).groupId;if(legacy&&!rows.some(x=>x.groupId===legacy))rows.push({id:'legacy-'+legacy,projectId:id,groupId:legacy,enabled:true,_legacy:true});return rows}
 async function addGroup(actorId,projectId,groupId){if(!await TM.Auth.can(actorId,'tasks.delegate'))throw Error('Permission denied');const rows=await groups(projectId);if(rows.some(x=>x.groupId===groupId))throw Error('Group already belongs to project');return TM.Store.addProjectGroup({projectId,groupId,actorId})}
 async function setGroups(actorId,projectId,groupIds=[]){if(!await TM.Auth.can(actorId,'tasks.delegate'))throw Error('Permission denied');const wanted=new Set(groupIds.filter(Boolean)),all=(await TM.Store.list('projectGroup')).filter(x=>!x._corrupt&&x.projectId===projectId);for(const row of all){const s=await groupState(row),should=wanted.has(row.groupId);if(s.enabled!==should)await TM.Store.addProjectGroupEvent({projectGroupId:row.id,projectId,action:'setEnabled',value:should,actorId});wanted.delete(row.groupId)}for(const groupId of wanted)await TM.Store.addProjectGroup({projectId,groupId,actorId});return groups(projectId)}
 async function create(actorId,{name,description='',groupIds=[]}){name=clean(name);if(!name)throw Error('Project name required');if(!await TM.Auth.can(actorId,'tasks.create'))throw Error('Permission denied');const existing=await list();if(existing.some(p=>p.status!=='Archived'&&clean(p.name).toLowerCase()===name.toLowerCase()))throw Error('Project name already exists');const p=await TM.Store.createProject({name,description:clean(description),ownerId:actorId,groupId:null,status:'Active'});for(const groupId of [...new Set(groupIds.filter(Boolean))])await TM.Store.addProjectGroup({projectId:p.id,groupId,actorId});return p}
 async function update(actorId,id,{name,description}){if(!await TM.Auth.can(actorId,'tasks.edit'))throw Error('Permission denied');const p=await state(id);if(name!==undefined&&clean(name)!==p.name)await TM.Store.addProjectEvent({projectId:id,action:'setName',value:clean(name),actorId});if(description!==undefined&&clean(description)!==p.description)await TM.Store.addProjectEvent({projectId:id,action:'setDescription',value:clean(description),actorId});return state(id)}
 async function setStatus(actorId,id,status){if(!await TM.Auth.can(actorId,'tasks.edit'))throw Error('Permission denied');if(!['Active','On Hold','Completed','Archived'].includes(status))throw Error('Invalid project status');await TM.Store.addProjectEvent({projectId:id,action:'setStatus',value:status,actorId});return state(id)}
 async function members(id){const rows=(await TM.Store.list('projectMember')).filter(x=>!x._corrupt&&x.projectId===id);return rows.filter(x=>x.enabled!==false)}
 async function addMember(actorId,projectId,userId,role='member'){if(!await TM.Auth.can(actorId,'tasks.delegate'))throw Error('Permission denied');const rows=await members(projectId);if(rows.some(x=>x.userId===userId))throw Error('User already belongs to project');return TM.Store.addProjectMember({projectId,userId,role,actorId})}
 return{state,list,groups,addGroup,setGroups,create,update,setStatus,members,addMember};
})();
