window.TM=window.TM||{};
TM.Projects=(()=>{
 const clean=v=>String(v??'').trim();
 async function state(id){const base=await TM.Store.get('project',id),s={...base};const events=(await TM.Store.list('projectEvent')).filter(e=>!e._corrupt&&e.projectId===id).sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt))||a.id.localeCompare(b.id));for(const e of events){if(e.action==='setName')s.name=e.value;if(e.action==='setDescription')s.description=e.value;if(e.action==='setStatus')s.status=e.value;if(e.action==='setStartDate')s.startDate=e.value||null;if(e.action==='setTargetDate')s.targetDate=e.value||null;if(e.action==='setCompletedAt')s.completedAt=e.value||null}return s}
 async function list(){const out=[];for(const p of (await TM.Store.list('project')).filter(x=>!x._corrupt))out.push(await state(p.id));return out}
 async function groupState(row){const s={...row};const es=(await TM.Store.list('projectGroupEvent')).filter(e=>!e._corrupt&&e.projectGroupId===row.id).sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt))||a.id.localeCompare(b.id));for(const e of es)if(e.action==='setEnabled')s.enabled=!!e.value;return s}
 async function groups(id){const rows=[];for(const x of (await TM.Store.list('projectGroup')).filter(x=>!x._corrupt&&x.projectId===id)){const s=await groupState(x);if(s.enabled!==false)rows.push(s)}const legacy=(await state(id)).groupId;if(legacy&&!rows.some(x=>x.groupId===legacy))rows.push({id:'legacy-'+legacy,projectId:id,groupId:legacy,enabled:true,_legacy:true});return rows}
 async function userGroupIds(userId){const ids=new Set();for(const m of (await TM.Store.list('membership')).filter(x=>!x._corrupt&&x.userId===userId&&x.groupId)){if((await TM.Identity.membershipState(m)).enabled)ids.add(m.groupId)}return ids}
 async function canAccess(userId,projectId){if(await TM.Auth.can(userId,'*'))return true;const mine=await userGroupIds(userId),pg=await groups(projectId);return pg.some(x=>mine.has(x.groupId))}
 async function listForUser(userId){const out=[];for(const p of await list())if(await canAccess(userId,p.id))out.push(p);return out}
 async function requireAccess(userId,projectId){if(!await canAccess(userId,projectId))throw Error('Project access denied')}
 async function addGroup(actorId,projectId,groupId){if(!await TM.Auth.can(actorId,'tasks.delegate'))throw Error('Permission denied');const rows=await groups(projectId);if(rows.some(x=>x.groupId===groupId))throw Error('Group already belongs to project');return TM.Store.addProjectGroup({projectId,groupId,actorId})}
 async function setGroups(actorId,projectId,groupIds=[]){if(!await TM.Auth.can(actorId,'tasks.delegate'))throw Error('Permission denied');const p=await state(projectId);if(['Completed','Archived'].includes(p.status))throw Error('Completed or archived projects cannot change groups');const wanted=new Set(groupIds.filter(Boolean)),all=(await TM.Store.list('projectGroup')).filter(x=>!x._corrupt&&x.projectId===projectId),activeTasks=await TM.Tasks.list(projectId);for(const row of all){const s=await groupState(row),should=wanted.has(row.groupId);if(s.enabled&&!should&&activeTasks.some(t=>t.responsibleGroupId===row.groupId&&!['Completed','Cancelled'].includes(t.status)))throw Error('Cannot remove a project group with active tasks');if(s.enabled!==should)await TM.Store.addProjectGroupEvent({projectGroupId:row.id,projectId,action:'setEnabled',value:should,actorId});wanted.delete(row.groupId)}for(const groupId of wanted)await TM.Store.addProjectGroup({projectId,groupId,actorId});return groups(projectId)}
 async function comments(id){return (await TM.Store.list('projectComment')).filter(x=>!x._corrupt&&x.projectId===id).sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)))}
 async function addComment(actorId,id,html){await requireAccess(actorId,id);html=String(html||'').trim();if(!html)throw Error('Comment required');return TM.Store.addProjectComment({projectId:id,authorId:actorId,html})}
 async function create(actorId,{name,description='',groupIds=[],startDate=null,targetDate=null}){name=clean(name);if(!name)throw Error('Project name required');if(!await TM.Auth.can(actorId,'tasks.create'))throw Error('Permission denied');const existing=await list();if(existing.some(p=>p.status!=='Archived'&&clean(p.name).toLowerCase()===name.toLowerCase()))throw Error('Project name already exists');const p=await TM.Store.createProject({name,description:clean(description),ownerId:actorId,groupId:null,status:'Active',startDate:startDate||null,targetDate:targetDate||null});for(const groupId of [...new Set(groupIds.filter(Boolean))])await TM.Store.addProjectGroup({projectId:p.id,groupId,actorId});return p}
 async function update(actorId,id,{name,description,startDate,targetDate}){if(!await TM.Auth.can(actorId,'tasks.edit'))throw Error('Permission denied');const p=await state(id);if(p.status==='Archived')throw Error('Archived projects cannot be edited');if(name!==undefined&&clean(name)!==p.name)await TM.Store.addProjectEvent({projectId:id,action:'setName',value:clean(name),actorId});if(description!==undefined&&clean(description)!==p.description)await TM.Store.addProjectEvent({projectId:id,action:'setDescription',value:clean(description),actorId});if(startDate!==undefined&&(startDate||null)!==(p.startDate||null))await TM.Store.addProjectEvent({projectId:id,action:'setStartDate',value:startDate||null,actorId});if(targetDate!==undefined&&(targetDate||null)!==(p.targetDate||null))await TM.Store.addProjectEvent({projectId:id,action:'setTargetDate',value:targetDate||null,actorId});return state(id)}
 async function setStatus(actorId,id,status){if(!await TM.Auth.can(actorId,'tasks.edit'))throw Error('Permission denied');if(!['Active','On Hold','Completed','Archived'].includes(status))throw Error('Invalid project status');const current=await state(id);if(current.status==='Archived'&&status!=='Active')throw Error('Archived projects must be restored before changing status');if(status==='Completed'){const open=(await TM.Tasks.list(id)).filter(t=>!['Completed','Cancelled'].includes(t.status));if(open.length)throw Error('Complete or cancel all project tasks before completing the project')}await TM.Store.addProjectEvent({projectId:id,action:'setStatus',value:status,actorId});const p=await state(id);if(status==='Completed'&&!p.completedAt)await TM.Store.addProjectEvent({projectId:id,action:'setCompletedAt',value:new Date().toISOString(),actorId});return state(id)}
 async function members(id){const rows=(await TM.Store.list('projectMember')).filter(x=>!x._corrupt&&x.projectId===id);return rows.filter(x=>x.enabled!==false)}
 async function addMember(actorId,projectId,userId,role='member'){if(!await TM.Auth.can(actorId,'tasks.delegate'))throw Error('Permission denied');const rows=await members(projectId);if(rows.some(x=>x.userId===userId))throw Error('User already belongs to project');return TM.Store.addProjectMember({projectId,userId,role,actorId})}
 async function timeline(id){const p=await state(id),tasks=await TM.Tasks.list(id),events=[];if(p.startDate)events.push({date:p.startDate,label:'Project start',kind:'project'});for(const t of tasks){events.push({date:t.createdAt,label:'Task created: '+t.title,kind:'task'});if(t.dueAt)events.push({date:t.dueAt,label:'Task due: '+t.title,kind:'due'});const tes=(await TM.Store.list('taskEvent')).filter(e=>!e._corrupt&&e.taskId===t.id&&e.action==='setStatus');for(const e of tes)events.push({date:e.createdAt,label:t.title+' → '+e.value,kind:'status'})}if(p.targetDate)events.push({date:p.targetDate,label:'Project target',kind:'target'});if(p.completedAt)events.push({date:p.completedAt,label:'Project completed',kind:'complete'});return events.filter(e=>e.date).sort((a,b)=>String(a.date).localeCompare(String(b.date)))}
 return{state,list,listForUser,canAccess,requireAccess,groups,addGroup,setGroups,create,update,setStatus,members,addMember,timeline};
})();
