(()=>{
window.TM=window.TM||{};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function render(id){
 const [p,events,tasks,users,groups]=await Promise.all([TM.DB.get('projects',Number(id)),TM.DB.allByIndex('projectEvents','projectId',Number(id)),TM.DB.getAll('tasks'),TM.DB.getAll('users'),TM.DB.getAll('groups')]);
 if(!p)return;
 events.sort((a,b)=>a.createdAt.localeCompare(b.createdAt));
 const own=tasks.filter(t=>Number(t.projectId)===Number(p.id)),owner=users.find(u=>u.id===p.ownerUserId),group=groups.find(g=>g.id===p.groupId),finished=own.filter(t=>TM.Work.taskBucket(t)==='Finished').length,late=own.filter(t=>TM.Work.taskBucket(t)==='Late').length,open=own.filter(t=>['New','In Progress'].includes(TM.Work.taskBucket(t))).length,pct=own.length?Math.round(finished/own.length*100):0;
 document.querySelectorAll('.nav button[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page==='projects'));
 document.querySelector('#page-content').innerHTML=`<div class="page-head"><button class="secondary" id="project-back">← Projects</button></div><div class="task-detail-head"><div><span class="work-code">${esc(p.code)}</span><h1>${esc(p.name)}</h1><p>${esc(p.description||'No description')}</p></div><div><span class="badge">${esc(p.status||'Active')}</span><p>${esc(group?.name||'No group')}</p><p>Owner: ${esc(owner?.displayName||owner?.username||'Unassigned')}</p>${p.expectedFinish?`<p>Expected: ${new Date(p.expectedFinish).toLocaleString()}</p>`:''}</div></div><section class="card"><div class="group-stats"><div><span>Open</span><strong>${open}</strong></div><div><span>Finished</span><strong>${finished}</strong></div><div><span>Late</span><strong>${late}</strong></div><div><span>Completion</span><strong>${pct}%</strong></div></div><div class="group-progress"><progress max="100" value="${pct}"></progress></div></section><section class="task-list-section"><div class="task-list-head"><div><h2>Project tasks</h2><p class="muted">${own.length} task${own.length===1?'':'s'} linked to this project</p></div></div><div class="project-grid">${own.length?own.map(t=>`<article class="work-card project-task-link" data-project-task="${t.id}"><div><span class="work-code">${esc(t.code)}</span><span class="badge">${esc(TM.Work.taskBucket(t))}</span></div><h3>${esc(t.title)}</h3><small>${esc(users.find(u=>u.id===t.assigneeUserId)?.displayName||users.find(u=>u.id===t.assigneeUserId)?.username||'Unassigned')} · ${esc(t.priority||'Normal')}</small><p>Expected: ${new Date(t.expectedFinish).toLocaleString()}</p></article>`).join(''):'<div class="card"><p class="muted">No tasks linked to this project yet.</p></div>'}</div></section><section class="timeline-shell"><div class="timeline">${events.map((e,i)=>{const u=users.find(x=>x.id===e.actorUserId);return `<article class="timeline-event ${i%2?'above':'below'}"><span class="timeline-dot"></span><div class="timeline-box"><strong>#${i+1} ${esc(u?.displayName||u?.username||'System')}</strong><small>${new Date(e.createdAt).toLocaleString()} · ${esc(e.type)}</small><p>${esc(e.text)}</p></div></article>`}).join('')||'<p class="muted">No project lifecycle events yet.</p>'}</div></section>`;
 document.querySelector('#project-back').onclick=()=>TM.Stage03.projectsPage();
 document.querySelectorAll('[data-project-task]').forEach(x=>x.onclick=()=>TM.TaskDetailV2.render(Number(x.dataset.projectTask)));
}
document.addEventListener('click',e=>{const hit=e.target.closest('[data-project]');if(!hit)return;e.preventDefault();e.stopImmediatePropagation();render(Number(hit.dataset.project))},true);
TM.ProjectDetail={render};
})();