window.TM=window.TM||{};
TM.StressTest=(()=>{
 const CONFIG={users:25,groups:3,projects:50,projectTasks:5,taskComments:5,standaloneTasks:500,tickets:500,actions:250,actionComments:5,personalNotes:25,personalPhones:25,personalEmails:25,leaveDays:15};
 const pad=(n,w=4)=>String(n).padStart(w,'0'),pick=(a,n)=>a[n%a.length],iso=d=>d.toISOString().slice(0,10);
 async function clearAndFillLeaves(actorId,year=new Date().getFullYear(),progress=()=>{}){if(!actorId||!await TM.Auth.can(actorId,'*'))throw Error('Administrator permission required');const allUsers=(await TM.Store.list('user')).filter(x=>!x._corrupt),users=allUsers.filter(x=>String(x.username||'').startsWith('DUMMY.LOAD.'));if(!users.length)throw Error('No DUMMY load-test users found');const leaves=(await TM.Store.list('publicLeave')).filter(x=>!x._corrupt),events=(await TM.Store.list('publicLeaveEvent')).filter(x=>!x._corrupt);let removed=0;for(const row of leaves){if(String(row.title||'').startsWith('DUMMY.LEAVE.')){await TM.FileSystem.remove(['Task-Management-Data','Leaves','Records'],row.id+'.json');removed++;for(const ev of events.filter(e=>e.leaveId===row.id))try{await TM.FileSystem.remove(['Task-Management-Data','Leaves','Events'],ev.id+'.json')}catch{}}}progress('Cleared '+removed+' DUMMY leave records.');for(let i=0;i<users.length;i++){const month=i%12,day=2+((i*7)%20),start=new Date(Date.UTC(year,month,day)),end=new Date(start);end.setUTCDate(end.getUTCDate()+CONFIG.leaveDays-1);await TM.Store.create('publicLeave',{ownerId:users[i].id,title:'DUMMY.LEAVE.'+CONFIG.leaveDays+'-DAYS.'+pad(i+1,3),startDate:iso(start),endDate:iso(end),note:'DUMMY '+CONFIG.leaveDays+'-day load-test leave · spread across year'});progress('Leaves: '+(i+1)+'/'+users.length)}return{cleared:removed,created:users.length,year}}
 async function fillActions(actorId,progress=()=>{}){if(!actorId||!await TM.Auth.can(actorId,'*'))throw Error('Administrator permission required');const users=(await TM.Store.list('user')).filter(x=>!x._corrupt&&String(x.username||'').startsWith('DUMMY.LOAD.')),groups=(await TM.Store.list('group')).filter(x=>!x._corrupt&&String(x.name||'').startsWith('DUMMY.GROUP.LOAD-'));if(!users.length)throw Error('No DUMMY load-test users found');const existing=(await TM.Store.list('actionRecord')).filter(x=>!x._corrupt&&String(x.target||'').startsWith('DUMMY.ACTION.TARGET.'));if(existing.length)throw Error('DUMMY actions already exist: '+existing.length);for(let n=1;n<=CONFIG.actions;n++){const actor=users[(n-1)%users.length],group=groups.length?groups[(n-1)%groups.length]:null,a=await TM.Store.createActionRecord({actorId:actor.id,actionType:pick(['Block Internal IP','Block External IP','Block Domain / URL','Disable Account','Isolate Endpoint','Change Firewall Rule','Change Domain Policy','Other'],n),target:'DUMMY.ACTION.TARGET.'+pad(n),reason:'DUMMY action reason '+n,details:'DUMMY operational action details for load test '+n,impact:'DUMMY impact scope '+((n%10)+1),evidence:'DUMMY-EVIDENCE-'+pad(n),groupId:group?.id||null});for(let x=1;x<=CONFIG.actionComments;x++)await TM.Store.addActionComment({actionId:a.id,authorId:users[(n+x)%users.length].id,html:'<p>DUMMY action comment '+x+' for action '+n+'</p>'});if(n%25===0)progress('Actions: '+n+'/'+CONFIG.actions)}return{actions:CONFIG.actions,comments:CONFIG.actions*CONFIG.actionComments}}
 async function generate(actorId,progress=()=>{}){
  if(!actorId)throw Error('Administrator required');
  if(!await TM.Auth.can(actorId,'*'))throw Error('Administrator permission required');
  const existing=(await TM.Store.list('user')).filter(x=>!x._corrupt&&String(x.username||'').startsWith('DUMMY.LOAD.'));
  if(existing.length)throw Error('DUMMY load-test data already exists in this workspace. Use a fresh test workspace.');
  const roles=(await TM.Store.list('role')).filter(x=>!x._corrupt),employee=roles.find(x=>x.systemKey==='employee');
  if(!employee)throw Error('Employee role not found');
  const groups=[],users=[],projects=[],allTasks=[];
  progress('Creating '+CONFIG.groups+' DUMMY groups…');
  for(let i=1;i<=CONFIG.groups;i++)groups.push(await TM.Store.createGroup({name:'DUMMY.GROUP.LOAD-'+pad(i,2),description:'DUMMY load-test group '+i}));
  progress('Creating '+CONFIG.users+' DUMMY users…');
  for(let i=1;i<=CONFIG.users;i++){const u=await TM.Store.createUser({username:'DUMMY.LOAD.USER.'+pad(i,3),displayName:'DUMMY Load User '+pad(i,3),enabled:true});users.push(u);await TM.Store.addMembership({userId:u.id,groupId:groups[(i-1)%groups.length].id,roleId:employee.id})}
  progress('Creating '+CONFIG.projects+' projects × '+CONFIG.projectTasks+' tasks × '+CONFIG.taskComments+' comments…');
  for(let p=1;p<=CONFIG.projects;p++){
   const g=groups[(p-1)%groups.length],owner=users[(p-1)%users.length];
   const pr=await TM.Store.createProject({name:'DUMMY.PROJECT.'+pad(p,3),description:'DUMMY load-test project '+p,ownerId:owner.id,groupId:g.id,status:pick(['Active','Active','On Hold','Completed'],p),startDate:'2026-09-01',targetDate:'2026-12-31'});projects.push(pr);
   await TM.Store.addProjectGroup({projectId:pr.id,groupId:g.id,actorId});
   for(let t=1;t<=CONFIG.projectTasks;t++){const n=(p-1)*CONFIG.projectTasks+t,assignee=users.find((u,idx)=>idx%groups.length===(p-1)%groups.length)||owner,task=await TM.Store.createTask({projectId:pr.id,responsibleGroupId:g.id,title:'DUMMY.TASK.PROJECT-'+pad(n),description:'DUMMY project task '+n,creatorId:owner.id,assigneeId:assignee.id,priority:pick(['Low','Normal','High','Critical'],n),status:pick(['Assigned','In Progress','Pending Review','Completed'],n),dueAt:'2026-10-'+pad((n%28)+1,2)});allTasks.push(task);for(let c=1;c<=CONFIG.taskComments;c++)await TM.Store.addTaskComment({taskId:task.id,authorId:users[(n+c)%users.length].id,html:'<p>DUMMY comment '+c+' for project task '+n+'</p>'});}
   if(p%10===0)progress('Projects: '+p+'/'+CONFIG.projects+' · task comments: '+(p*CONFIG.projectTasks*CONFIG.taskComments));
  }
  progress('Creating '+CONFIG.standaloneTasks+' standalone tasks × '+CONFIG.taskComments+' comments…');
  for(let n=1;n<=CONFIG.standaloneTasks;n++){const g=groups[(n-1)%groups.length],creator=users[(n-1)%users.length],assignee=users.find((u,idx)=>idx%groups.length===(n-1)%groups.length)||creator,task=await TM.Store.createTask({responsibleGroupId:g.id,title:'DUMMY.TASK.STANDALONE-'+pad(n),description:'DUMMY standalone load-test task '+n,creatorId:creator.id,assigneeId:assignee.id,priority:pick(['Low','Normal','High','Critical'],n),status:pick(['Assigned','In Progress','Blocked','Pending Review','Completed'],n),dueAt:'2026-11-'+pad((n%28)+1,2)});allTasks.push(task);for(let c=1;c<=CONFIG.taskComments;c++)await TM.Store.addTaskComment({taskId:task.id,authorId:users[(n+c)%users.length].id,html:'<p>DUMMY comment '+c+' for standalone task '+n+'</p>'});if(n%100===0)progress('Standalone tasks: '+n+'/'+CONFIG.standaloneTasks);}
  progress('Creating '+CONFIG.tickets+' tickets…');
  for(let n=1;n<=CONFIG.tickets;n++){const g=groups[(n-1)%groups.length],requester=users[(n-1)%users.length],assignee=users.find((u,idx)=>idx%groups.length===(n-1)%groups.length)||requester;await TM.Store.createTicket({requesterId:requester.id,responsibleGroupId:g.id,title:'DUMMY.TICKET.'+pad(n),description:'DUMMY load-test ticket '+n,priority:pick(['Low','Normal','High','Critical'],n),assigneeId:assignee.id,status:pick(['Open','Assigned','In Progress','Pending Resolution','Resolved','Closed'],n)});if(n%100===0)progress('Tickets: '+n+'/'+CONFIG.tickets);}
  progress('Creating '+CONFIG.actions+' DUMMY actions × '+CONFIG.actionComments+' comments…');
  await fillActions(actorId,progress);
  progress('Creating '+CONFIG.leaveDays+'-day leave for all '+CONFIG.users+' users…');
  for(let i=0;i<users.length;i++){const month=i%12,day=2+((i*7)%20),start=new Date(Date.UTC(2026,month,day)),end=new Date(start);end.setUTCDate(end.getUTCDate()+CONFIG.leaveDays-1);await TM.Store.create('publicLeave',{ownerId:users[i].id,title:'DUMMY.LEAVE.'+CONFIG.leaveDays+'-DAYS.'+pad(i+1,3),startDate:iso(start),endDate:iso(end),note:'DUMMY '+CONFIG.leaveDays+'-day load-test leave · spread across year'})}
  progress('Creating Personal Workspace test records for the current administrator…');
  for(let i=1;i<=CONFIG.personalNotes;i++)await TM.PersonalDB.put('notes',actorId,{id:'DUMMY.LOAD.NOTE.'+pad(i,3),title:'DUMMY Note '+pad(i,3),body:'DUMMY personal workspace load-test note '+i,tags:'DUMMY,load-test'});
  for(let i=1;i<=CONFIG.personalPhones;i++)await TM.PersonalDB.put('phonebook',actorId,{id:'DUMMY.LOAD.PHONE.'+pad(i,3),name:'DUMMY Contact '+pad(i,3),organization:'DUMMY Organization',phone:'+968 90'+pad(i,6),extension:pad(i,3),notes:'DUMMY phone-book load test'});
  for(let i=1;i<=CONFIG.personalEmails;i++)await TM.PersonalDB.put('emailbook',actorId,{id:'DUMMY.LOAD.EMAIL.'+pad(i,3),name:'DUMMY Mail Contact '+pad(i,3),organization:'DUMMY Organization',email:'dummy.load.'+pad(i,3)+'@example.test',notes:'DUMMY email-book load test'});
  const summary={users:users.length,groups:groups.length,projects:projects.length,projectTasks:CONFIG.projects*CONFIG.projectTasks,standaloneTasks:CONFIG.standaloneTasks,taskComments:(CONFIG.projects*CONFIG.projectTasks+CONFIG.standaloneTasks)*CONFIG.taskComments,tickets:CONFIG.tickets,actions:CONFIG.actions,actionComments:CONFIG.actions*CONFIG.actionComments,leaves:users.length,personalNotes:CONFIG.personalNotes,personalPhones:CONFIG.personalPhones,personalEmails:CONFIG.personalEmails};
  localStorage.setItem('tm-load-test-summary',JSON.stringify({...summary,generatedAt:new Date().toISOString()}));progress('Load-test environment complete.');return summary;
 }
 return{CONFIG,generate,clearAndFillLeaves,fillActions};
})();