window.TM=window.TM||{};
TM.Tasks=(()=>{
 const STATUSES=['Draft','Pending Group Acceptance','Assigned','Accepted','In Progress','Blocked','Pending Review','Completed','Returned','Cancelled'],PRIORITIES=['Low','Normal','High','Critical'],clean=v=>String(v??'').trim();
 async function state(id){const base=await TM.Store.get('task',id),s={...base};const es=(await TM.Store.list('taskEvent')).filter(e=>!e._corrupt&&e.taskId===id).sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt))||a.id.localeCompare(b.id));for(const e of es){if(e.action==='setTitle')s.title=e.value;if(e.action==='setDescription')s.description=e.value;if(e.action==='setStatus')s.status=e.value;if(e.action==='setAssignee')s.assigneeId=e.value||null;if(e.action==='setResponsibleGroup')s.responsibleGroupId=e.value;if(e.action==='setPriority')s.priority=e.value;if(e.action==='setDueAt')s.dueAt=e.value||null;if(e.action==='acceptGroup')s.groupAcceptedBy=e.actorId;if(e.action==='returnGroup')s.returnReason=e.value}return s}
 async function list(projectId=null){const out=[];for(const t of (await TM.Store.list('task')).filter(x=>!x._corrupt&&(!projectId||x.projectId===projectId)))out.push(await state(t.id));return out}
 async function roleMap(){return new Map((await TM.Store.list('role')).filter(x=>!x._corrupt).map(r=>[r.id,r]))}
 async function leaderGroups(userId){const roles=await roleMap(),ids=new Set();for(const m of (await TM.Store.list('membership')).filter(x=>!x._corrupt&&x.userId===userId&&x.groupId)){if(!(await TM.Identity.membershipState(m)).enabled)continue;const r=roles.get(m.roleId);if(r?.systemKey==='team_leader'||r?.systemKey==='manager'||r?.systemKey==='administrator')ids.add(m.groupId)}return ids}
 async function isLeaderFor(userId,groupId){if(await TM.Auth.can(userId,'*'))return true;return (await leaderGroups(userId)).has(groupId)}
 async function validMember(userId,groupId){for(const m of (await TM.Store.list('membership')).filter(x=>!x._corrupt&&x.userId===userId&&x.groupId===groupId))if((await TM.Identity.membershipState(m)).enabled)return true;return false}
 async function create(actorId,{projectId=null,responsibleGroupId,title,description='',assigneeId=null,priority='Normal',dueAt=null}){title=clean(title);if(!title)throw Error('Task title required');if(!responsibleGroupId)throw Error('Responsible group required');if(!PRIORITIES.includes(priority))throw Error('Invalid priority');if(!await TM.Auth.can(actorId,'tasks.create'))throw Error('Permission denied');if(projectId){await TM.Projects.requireAccess(actorId,projectId);const pg=await TM.Projects.groups(projectId);if(!pg.some(x=>x.groupId===responsibleGroupId))throw Error('Responsible group is not part of this project')}const own=await isLeaderFor(actorId,responsibleGroupId);if(!own&&assigneeId)throw Error('Cross-group tasks must be accepted and assigned by the destination Team Leader');if(assigneeId&&!await validMember(assigneeId,responsibleGroupId))throw Error('Assignee must belong to the responsible group');const status=own?(assigneeId?'Assigned':'Draft'):'Pending Group Acceptance';return TM.Store.createTask({projectId,responsibleGroupId,title,description:clean(description),creatorId:actorId,assigneeId:own?assigneeId:null,priority,status,dueAt:dueAt||null})}
 async function acceptGroup(actorId,id){const t=await state(id);if(t.status!=='Pending Group Acceptance')throw Error('Task is not awaiting group acceptance');if(!await isLeaderFor(actorId,t.responsibleGroupId))throw Error('Only the destination Team Leader can accept this task');await TM.Store.addTaskEvent({taskId:id,action:'acceptGroup',value:true,actorId});await TM.Store.addTaskEvent({taskId:id,action:'setStatus',value:'Draft',actorId});return state(id)}
 async function returnGroup(actorId,id,reason){reason=clean(reason);if(!reason)throw Error('Return reason required');const t=await state(id);if(t.status!=='Pending Group Acceptance')throw Error('Task is not awaiting group acceptance');if(!await isLeaderFor(actorId,t.responsibleGroupId))throw Error('Only the destination Team Leader can return this task');await TM.Store.addTaskEvent({taskId:id,action:'returnGroup',value:reason,actorId});await TM.Store.addTaskEvent({taskId:id,action:'setStatus',value:'Returned',actorId});return state(id)}
 async function setStatus(actorId,id,status){if(!STATUSES.includes(status))throw Error('Invalid task status');const t=await state(id);if(t.projectId)await TM.Projects.requireAccess(actorId,t.projectId);if(t.status==='Pending Group Acceptance')throw Error('Destination Team Leader must accept or return this task first');const own=t.assigneeId===actorId;if(!await TM.Auth.can(actorId,'tasks.edit')&&!(own&&await TM.Auth.can(actorId,'tasks.updateOwn')))throw Error('Permission denied');await TM.Store.addTaskEvent({taskId:id,action:'setStatus',value:status,actorId});return state(id)}
 async function assign(actorId,id,userId){if(!await TM.Auth.can(actorId,'tasks.delegate'))throw Error('Permission denied');const t=await state(id);if(t.projectId)await TM.Projects.requireAccess(actorId,t.projectId);if(t.status==='Pending Group Acceptance')throw Error('Accept the group handoff before assigning');if(!await isLeaderFor(actorId,t.responsibleGroupId))throw Error('Only the responsible group Team Leader can assign this task');if(userId&&!await validMember(userId,t.responsibleGroupId))throw Error('Assignee must belong to the responsible group');await TM.Store.addTaskEvent({taskId:id,action:'setAssignee',value:userId||null,actorId});if(userId&&(t.status==='Draft'||t.status==='Returned'))await TM.Store.addTaskEvent({taskId:id,action:'setStatus',value:'Assigned',actorId});return state(id)}
 return{STATUSES,PRIORITIES,state,list,leaderGroups,isLeaderFor,create,acceptGroup,returnGroup,setStatus,assign};
})();
