window.TM=window.TM||{};
TM.Tasks=(()=>{
 const STATUSES=['Draft','Assigned','Accepted','In Progress','Blocked','Pending Review','Completed','Cancelled'],PRIORITIES=['Low','Normal','High','Critical'],clean=v=>String(v??'').trim();
 async function state(id){const base=await TM.Store.get('task',id),s={...base};const es=(await TM.Store.list('taskEvent')).filter(e=>!e._corrupt&&e.taskId===id).sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt))||a.id.localeCompare(b.id));for(const e of es){if(e.action==='setTitle')s.title=e.value;if(e.action==='setDescription')s.description=e.value;if(e.action==='setStatus')s.status=e.value;if(e.action==='setAssignee')s.assigneeId=e.value||null;if(e.action==='setResponsibleGroup')s.responsibleGroupId=e.value;if(e.action==='setPriority')s.priority=e.value;if(e.action==='setDueAt')s.dueAt=e.value||null}return s}
 async function list(projectId=null){const out=[];for(const t of (await TM.Store.list('task')).filter(x=>!x._corrupt&&(!projectId||x.projectId===projectId)))out.push(await state(t.id));return out}
 async function create(actorId,{projectId=null,responsibleGroupId,title,description='',assigneeId=null,priority='Normal',dueAt=null}){title=clean(title);if(!title)throw Error('Task title required');if(!responsibleGroupId)throw Error('Responsible group required');if(!PRIORITIES.includes(priority))throw Error('Invalid priority');if(!await TM.Auth.can(actorId,'tasks.create'))throw Error('Permission denied');const status=assigneeId?'Assigned':'Draft';if(projectId){await TM.Projects.requireAccess(actorId,projectId);const pg=await TM.Projects.groups(projectId);if(!pg.some(x=>x.groupId===responsibleGroupId))throw Error('Responsible group is not part of this project')}if(assigneeId){const memberships=(await TM.Store.list('membership')).filter(x=>!x._corrupt&&x.userId===assigneeId&&x.groupId===responsibleGroupId);let valid=false;for(const m of memberships)if((await TM.Identity.membershipState(m)).enabled){valid=true;break}if(!valid)throw Error('Assignee must belong to the responsible group')}return TM.Store.createTask({projectId,responsibleGroupId,title,description:clean(description),creatorId:actorId,assigneeId,priority,status,dueAt:dueAt||null})}
 async function setStatus(actorId,id,status){if(!STATUSES.includes(status))throw Error('Invalid task status');const t=await state(id);if(t.projectId)await TM.Projects.requireAccess(actorId,t.projectId);const own=t.assigneeId===actorId;if(!await TM.Auth.can(actorId,'tasks.edit')&&!(own&&await TM.Auth.can(actorId,'tasks.updateOwn')))throw Error('Permission denied');await TM.Store.addTaskEvent({taskId:id,action:'setStatus',value:status,actorId});return state(id)}
 async function assign(actorId,id,userId){if(!await TM.Auth.can(actorId,'tasks.delegate'))throw Error('Permission denied');const t0=await state(id);if(t0.projectId)await TM.Projects.requireAccess(actorId,t0.projectId);if(userId){const memberships=(await TM.Store.list('membership')).filter(x=>!x._corrupt&&x.userId===userId&&x.groupId===t0.responsibleGroupId);let valid=false;for(const m of memberships)if((await TM.Identity.membershipState(m)).enabled){valid=true;break}if(!valid)throw Error('Assignee must belong to the responsible group')}await TM.Store.addTaskEvent({taskId:id,action:'setAssignee',value:userId||null,actorId});if(userId){const t=await state(id);if(t.status==='Draft')await TM.Store.addTaskEvent({taskId:id,action:'setStatus',value:'Assigned',actorId})}return state(id)}
 return{STATUSES,PRIORITIES,state,list,create,setStatus,assign};
})();
