window.TM=window.TM||{};
TM.Tickets=(()=>{
 const STATUSES=['Open','Assigned','Accepted','In Progress','Pending Resolution','Resolved','Closed','Reopened','Cancelled'],PRIORITIES=['Low','Normal','High','Critical'],clean=v=>String(v??'').trim();
 async function state(id){const b=await TM.Store.get('ticket',id),s={...b};const es=(await TM.Store.list('ticketEvent')).filter(e=>!e._corrupt&&e.ticketId===id).sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt))||a.id.localeCompare(b.id));for(const e of es){if(e.action==='setStatus')s.status=e.value;if(e.action==='setAssignee')s.assigneeId=e.value||null;if(e.action==='setPriority')s.priority=e.value;if(e.action==='setResponsibleGroup')s.responsibleGroupId=e.value;if(e.action==='setResolution')s.resolution=e.value;if(e.action==='reopenReason')s.reopenReason=e.value}return s}
 async function list(){const out=[];for(const x of (await TM.Store.list('ticket')).filter(x=>!x._corrupt))out.push(await state(x.id));return out}
 async function validMember(userId,groupId){for(const m of (await TM.Store.list('membership')).filter(x=>!x._corrupt&&x.userId===userId&&x.groupId===groupId))if((await TM.Identity.membershipState(m)).enabled)return true;return false}
 async function leaderGroups(userId){if(await TM.Auth.can(userId,'*'))return new Set((await TM.Store.list('group')).filter(x=>!x._corrupt).map(x=>x.id));const roles=new Map((await TM.Store.list('role')).filter(x=>!x._corrupt).map(r=>[r.id,r])),out=new Set();for(const m of (await TM.Store.list('membership')).filter(x=>!x._corrupt&&x.userId===userId&&x.groupId)){if(!(await TM.Identity.membershipState(m)).enabled)continue;const k=roles.get(m.roleId)?.systemKey;if(['team_leader','manager','administrator'].includes(k))out.add(m.groupId)}return out}
 async function visible(userId){const admin=await TM.Auth.can(userId,'*'),leaders=await leaderGroups(userId),out=[];for(const t of await list())if(admin||t.requesterId===userId||t.assigneeId===userId||leaders.has(t.responsibleGroupId)||(!t.assigneeId&&await validMember(userId,t.responsibleGroupId)))out.push(t);return out}
 async function timeline(id){const t=await TM.Store.get('ticket',id),out=[{date:t.createdAt,label:'Ticket created',actorId:t.requesterId}];for(const e of (await TM.Store.list('ticketEvent')).filter(x=>!x._corrupt&&x.ticketId===id)){let label=e.action==='setStatus'?'Status → '+e.value:e.action==='setAssignee'?'Ticket assigned':e.action==='setResolution'?'Resolution submitted':e.action==='reopenReason'?'Ticket reopened':e.action;out.push({date:e.createdAt,label,actorId:e.actorId})}return out.sort((a,b)=>String(a.date).localeCompare(String(b.date)))}
 async function comments(id){return (await TM.Store.list('ticketComment')).filter(x=>!x._corrupt&&x.ticketId===id).sort((a,b)=>String(a.createdAt).localeCompare(String(b.createdAt)))}
 async function addComment(actorId,id,html){const allowed=(await visible(actorId)).some(x=>x.id===id);if(!allowed)throw Error('Ticket access denied');html=String(html||'').trim();if(!html)throw Error('Comment required');return TM.Store.addTicketComment({ticketId:id,authorId:actorId,html})}
 async function create(actorId,{responsibleGroupId,title,description='',priority='Normal'}){title=clean(title);if(!await TM.Auth.can(actorId,'tickets.create'))throw Error('Permission denied');if(!responsibleGroupId||!title)throw Error('Responsible group and title required');if(!PRIORITIES.includes(priority))throw Error('Invalid priority');return TM.Store.createTicket({requesterId:actorId,responsibleGroupId,title,description:clean(description),priority})}
 async function assign(actorId,id,userId){if(!await TM.Auth.can(actorId,'tickets.assign'))throw Error('Permission denied');const t=await state(id);if(['Resolved','Closed','Cancelled'].includes(t.status))throw Error('Terminal tickets cannot be assigned');if(!(await leaderGroups(actorId)).has(t.responsibleGroupId))throw Error('Only the responsible group Team Leader can assign this ticket');if(!await validMember(userId,t.responsibleGroupId))throw Error('Assignee must belong to the responsible group');await TM.Store.addTicketEvent({ticketId:id,action:'setAssignee',value:userId,actorId});await TM.Store.addTicketEvent({ticketId:id,action:'setStatus',value:'Assigned',actorId});return state(id)}
 async function allowedActions(actorId,id){const t=await state(id),leader=(await leaderGroups(actorId)).has(t.responsibleGroupId),assignee=t.assigneeId===actorId,requester=t.requesterId===actorId,close=await TM.Auth.can(actorId,'tickets.close'),a=[];if(t.status==='Assigned'&&assignee)a.push('accept');if(['Accepted','Reopened'].includes(t.status)&&assignee)a.push('start');if(t.status==='In Progress'&&assignee)a.push('submitResolution');if(t.status==='Pending Resolution'&&(leader||close))a.push('resolve','returnToWork');if(t.status==='Resolved'&&(requester||close))a.push('close','reopen');return a}
 async function transition(actorId,id,action,value=''){const allowed=await allowedActions(actorId,id);if(!allowed.includes(action))throw Error('Ticket transition not allowed');const next={accept:'Accepted',start:'In Progress',submitResolution:'Pending Resolution',resolve:'Resolved',returnToWork:'In Progress',close:'Closed',reopen:'Reopened'}[action];if(action==='submitResolution'){value=clean(value);if(!value)throw Error('Resolution notes required');await TM.Store.addTicketEvent({ticketId:id,action:'setResolution',value,actorId})}if(action==='reopen'){value=clean(value);if(!value)throw Error('Reopen reason required');await TM.Store.addTicketEvent({ticketId:id,action:'reopenReason',value,actorId})}await TM.Store.addTicketEvent({ticketId:id,action:'setStatus',value:next,actorId});return state(id)}
 return{STATUSES,PRIORITIES,state,list,visible,leaderGroups,timeline,comments,addComment,create,assign,allowedActions,transition};
})();